0-9 Murat
10-18 Yusuf
19-27 Ismail
27-36 Omer
37-39 Omer
40-42 Ismail
43-45 Yusuf
46-48  Murat

# Import necessary libraries

In [9]:
import pandas as pd
import re
import seaborn as sns
from numpy import nan
import numpy as np
import matplotlib.pyplot as plt
import missingno as msno

 # Return CSV as Pandas DataFrame

In [10]:
df_origin = pd.read_csv("data.csv")
df = df_origin.copy()
df.head()

,Unnamed: 0,location,make,model,short_description,price,mileage,gearbox,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,country_version,offer_number,warranty,Mileage,first_registration,production_date,general_inspection,last_service,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,Fuel_type,fuel_consumption,co2_emissions,emission_class,emissions_sticker,\nComfort & Convenience\n,\nEntertainment & Media\n,\nSafety & Security\n,extras,\ncolour,\nmanufacturer_color,\npaint,upholstery_colour,upholstery
0,0,"LOON OP ZAND, NL","\n,Audi ,\n","\n,A3,\n",2.0 FSI Ambition Pro Line,"[['\n', '€ 4,450.-', '\n']]","['', ['191,066 km']]","\n,Automatic,\n",08/2003,"\n,Gasoline,\n","110 kW (150 hp),","['\n', ['Dealer\n']]","\n,Compact,\n","\n,Used,\n","\n,Front,\n",\n5,\n3,"Country version,None",\nSJ-112-R,"\n,6 months,\n","[['\n'], ['']]",08/2003,NaN,05/2022,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,110 kW (150 hp),\n","\n,Automatic,\n","\n,1,984 cc,\n","\n,None,\n","\n,4,\n","\n,1,280 kg,\n","\n,Super 95,\n","\n,None,\n","['\n', [' ', ' ', ' '], '\n']","\n,Euro 4,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'Radio']]","[['ABS', 'Alarm system', 'Central door lock', ...",[['Alloy wheels']],"\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth"
1,1,"HEERLEN, NL","\n,Audi ,\n","\n,A3,\n",Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,"[['\n', '€ 12,950.-', '\n']]","['', ['94,758 km']]","\n,Automatic,\n",10/2013,"\n,Gasoline,\n","92 kW (125 hp),","['\n', ['Dealer\n']]","\n,Compact,\n","\n,Used,\n","\n,Front,\n",\n5,\n5,"Country version,None",\n809725,"\n,None,\n","[['\n'], ['']]",10/2013,NaN,NaN,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n","\n,Automatic,\n","\n,1,395 cc,\n","\n,None,\n","\n,4,\n","\n,1,200 kg,\n","\n,Gasoline,\n","['\n', ['4.9 l/100 km (comb.)', ' ', ' '], '\n']","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Automatic climate contr...","[['CD player', 'Radio']]","[['Alarm system', 'Central door lock', 'Centra...","[['Alloy wheels (16"")']]","\n4, White",NaN,NaN,"\nupholstery, Black","\n8, Cloth"
2,3,"BAARLE-NASSAU, NL","\n,Audi ,\n","\n,A1,\n",1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,"[['\n', '€ 12,450.-', '\n']]","['', ['145,102 km']]","\n,Automatic,\n",06/2015,"\n,Gasoline,\n","92 kW (125 hp),","['\n', ['Dealer\n']]","\n,Compact,\n","\n,Used,\n","\n,None,\n",\n5,\n5,"Country version,Netherlands",\n2601307,"\n,6 months,\n","[['\n'], ['']]",06/2015,2015.0,New,NaN,"\n,Yes,\n","\n,Yes,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n","\n,Automatic,\n","\n,1,395 cc,\n","\n,None,\n","\n,4,\n","\n,None,\n","\n,Gasoline,\n","['\n', ['0 l/100 km (comb.)', '0 l/100 km (cit...","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['Bluetooth', 'CD player', 'On-board computer...","[['ABS', 'Central door lock with remote contro...","[['Alloy wheels (15"")']]","\n4, Grey",NaN,"\npaint, Metallic",NaN,NaN
3,4,"ZUTPHEN, NL","\n,Audi ,\n","\n,A1,\n",S-Line | Automaat | Navigatie | Cruise-/Climat...,"[['\n', '€ 14,945.-', '\n']]","['', ['119,666 km']]","\n,Automatic,\n",10/2015,"\n,Gasoline,\n","92 kW (125 hp),","['\n', ['Dealer\n']]","\n,Compact,\n","\n,Used,\n","\n,Front,\n",\n4,\n3,"Country version,None",\nL-847-SK,"\n,6 months,\n","[['\n'], ['']]",10/2015,NaN,NaN,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n","\n,Automatic,\n","\n,1,395 cc,\n","\n,7,\n","\n,4,\n","\n,1,105 kg,\n","\n,Gasoline,\n","['\n', ['4.8 l/100 km (comb.)', '5.9 l/100 km ...","\n,111 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'MP3', 'On-board computer', 'Ra...","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Shift paddles', 'Spor...","\n4, Black",NaN,NaN,"\nupholstery, Black","\n8, Part leather"
4,7,"HAAKSBERGEN, NL","\n,Audi ,\n","\n,A3,\n",Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,"[['\n', '€ 24,900.-', '\n']]","['', ['55,815 km']]","\n,Automatic,\n",10/2017,"\n,Gasoline,\n","110 kW (150 hp),","['\n', ['Dealer\n']]","\n,Compact,\n","\n,Used,\n","\n,Front,\n",\n5,\n5,"Country version,None",\nPZ-744-H,"\n,6 months,\n","[['\n'], ['']]",10/2017,NaN,11/2023,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,110 kW (150 hp),\n","\n,Automatic,\n","\n,1,495 cc,\n","\n,7,\n","\n,4,\n","\n,1,215 kg,\n","\n,Super 95,\n","['\n', ['5 l/100 km (comb.)', '6.2 l/100 km (c...","\n,113 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Electrical s...","[['CD player', 'On-board computer', 'Radio']]","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Sport seats', 'Sport ...","\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth"

In [11]:
df.shape

(62766, 49)

In [12]:
df.isnull().sum()

Unnamed: 0                       0
location                         0
make                             0
model                            0
short_description              149
price                            0
mileage                          0
gearbox                          0
registration                    37
fuel_type                        0
power                            0
seller                           0
body_type                        0
type                             0
drivetrain                       0
seats                            0
doors                            0
country_version                  0
offer_number                     0
warranty                         0
Mileage                          0
first_registration              37
production_date              56210
general_inspection           15038
last_service                 62766
full_service_history             0
non_smoker_vehicle               0
previous_owner                   0
last_timing_belt_change          0
Power                            0
Gearbox                          0
engine_size                      0
gears                            0
cylinders                        0
empty_weight                     0
Fuel_type                        0
fuel_consumption                 0
co2_emissions                    0
emission_class                   0
emissions_sticker                0
\nComfort & Convenience\n        0
\nEntertainment & Media\n        0
\nSafety & Security\n            0
extras                           0
\ncolour                      1048
\nmanufacturer_color         62766
\npaint                      18343
 upholstery_colour           21886
 upholstery                  10683
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62766 entries, 0 to 62765
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               62766 non-null  int64
 1   location                 62766 non-null  object
 2   make                     62766 non-null  object
 3   model                    62766 non-null  object
 4   short_description        62617 non-null  object
 5   price                    62766 non-null  object
 6   mileage                  62766 non-null  object
 7   gearbox                  62766 non-null  object
 8   registration             62729 non-null  object
 9   fuel_type                62766 non-null  object
 10  power                    62766 non-null  object
 11  seller                   62766 non-null  object
 12  body_type                62766 non-null  object
 13  type                     62766 non-null  object
 14  drivetrain               62766 non-null  object
 15  seats                    62766 non-null  object
 16  doors                    62766 non-null  object
 17  country_version          62766 non-null  object
 18  offer_number             62766 non-null  object
 19  warranty                 62766 non-null  object
 20  Mileage                  62766 non-null  object
 21  first_registration       62729 non-null  object
 22  production_date          6556 non-null   float64
 23  general_inspection       47728 non-null  object
 24  last_service             0 non-null      float64
 25  full_service_history     62766 non-null  object
 26  non_smoker_vehicle       62766 non-null  object
 27  previous_owner           62766 non-null  object
 28  last_timing_belt_change  62766 non-null  object
 29  Power                    62766 non-null  object
 30  Gearbox                  62766 non-null  object
 31  engine_size              62766 non-null  object
 32  gears                    62766 non-null  object
 33  cylinders                62766 non-null  object
 34  empty_weight             62766 non-null  object
 35  Fuel_type                62766 non-null  object
 36  fuel_consumption         62766 non-null  object
 37  co2_emissions            62766 non-null  object
 38  emission_class           62766 non-null  object
 39  emissions_sticker        62766 non-null  object
 40
Comfort & Convenience
  62766 non-null  object
 41
Entertainment & Media
  62766 non-null  object
 42
Safety & Security
      62766 non-null  object
 43  extras                   62766 non-null  object
 44
colour                  61718 non-null  object
 45
manufacturer_color      0 non-null      float64
 46
paint                   44423 non-null  object
 47   upholstery_colour       40880 non-null  object
 48   upholstery              52083 non-null  object
dtypes: float64(3), int64(1), object(45)
memory usage: 23.5+ MB

In [244]:
df.nunique()

location                    1486
make                          20
model                        754
short_description          53144
price                       6523
mileage                    44162
registration                 303
fuel_type                     12
power                        356
body_type                     12
type                           5
drivetrain                     4
seats                         10
doors                          7
warranty                      17
production_date               35
general_inspection            92
full_service_history           2
non_smoker_vehicle             2
last_timing_belt_change       82
Gearbox                        4
engine_size                  443
gears                         10
cylinders                     10
empty_weight                1537
fuel_consumption            3731
co2_emissions ( g/km)        342
emission_class                10
emissions_sticker              6
comfort_convenience        28013
entertainment_media         1860
safety_security            19260
extras                      8380
colour                        14
paint                          2
upholstery_colour             11
upholstery                     6
warranty_category              3
full_service_encoded           2
non_smoker_encoded             2
fuel_cons_comb               186
fuel_cons_city               235
fuel_cons_country            133
air_conditioning              50
AppleCarPlay                  28
abs_encoded                   41
dtype: int64

In [15]:
df.describe()

         Unnamed: 0  production_date  last_service  \nmanufacturer_color
count  62766.000000      6556.000000           0.0                   0.0
mean   35563.827709      2014.969951           NaN                   NaN
std    20562.958458         5.392130           NaN                   NaN
min        0.000000      1997.000000           NaN                   NaN
25%    17718.250000      2011.000000           NaN                   NaN
50%    35595.500000      2016.000000           NaN                   NaN
75%    53391.750000      2020.000000           NaN                   NaN
max    71103.000000      2022.000000           NaN                   NaN

In [220]:
df.drop("Unnamed: 0", inplace=True, axis=1)

# 1-location

In [17]:

# Capitalize all the data in the 'location' column
df['location'] = df['location'].str.upper()

# Delete punctuation and numeric values from words before 'NL'
df['location'] = df['location'].apply(lambda x: re.sub(r'[^\w\s]*\d*', '', x.split(',')[0]) + ',NL')
df['location'] = df['location'].apply(lambda x: re.sub(r"\bSGRAVEV", r"'S-GRAVE", x))

# Replace locations without a city name with the region where the most vehicle sales are made in the Netherlands.
df.loc[df['location'] == ',NL', 'location'] = 'AMSTERDAM ZUIDOOST,NL'

# Replace some cities that require special spelling.
city_mapping = {
    'GRAVENHAGE': "'S-GRAVENHAGE, NL",
    'HERTOGENBOSCH': "'S-HERTOGENBOSCH, NL",
    'GRAVENZANDE': "'S-GRAVENZANDE, NL",
    'HEER ARENDSKERKE': "'S-HEER ARENDSKERKE, NL",
    'GRAVENPOLDER': "'S-GRAVENPOLDER, NL",
    'GRAVENDEEL': "'S-GRAVENDEEL, NL",
    'GRAVENLAND': "'S-GRAVENLAND, NL",
    'HEERENBERG': "'S-HEERENBERG, NL",
    'HARDE': "'T-HARDE, NL",
    'T ZAND': "'T-ZAND, NL",
    'GOY': "'T-GOY, NL",
    'BERGEN': "BERGEN, NL",
    'AMSTERDAMZUIDOOST': "AMSTERDAM ZUIDOOST,NL"
}

df['location'] = df['location'].replace(city_mapping)

df["location"].head()

0    LOON OP ZAND,NL
1         HEERLEN,NL
2    BAARLENASSAU,NL
3         ZUTPHEN,NL
4     HAAKSBERGEN,NL
Name: location, dtype: object

# 2-make

In [18]:
df["make"]

0         \n,Audi ,\n
1         \n,Audi ,\n
2         \n,Audi ,\n
3         \n,Audi ,\n
4         \n,Audi ,\n
             ...
62761    \n,Volvo ,\n
62762    \n,Volvo ,\n
62763    \n,Volvo ,\n
62764    \n,Volvo ,\n
62765    \n,Volvo ,\n
Name: make, Length: 62766, dtype: object

In [19]:
df["make"]=df["make"].str.strip(',\n\r')
df['make'].value_counts()

make
BMW               6942
Volkswagen        6436
Mercedes-Benz     5860
Audi              5675
Volvo             4734
Renault           4255
Ford              4036
Peugeot           3492
Toyota            2783
Skoda             2588
Kia               2502
Opel              2342
Hyundai           2271
Mazda             2161
Citroen           2146
Fiat              1923
Honda              948
Dacia              829
Chevrolet          427
Tesla              416
Name: count, dtype: int64

# 3-model

In [20]:
df["model"]

0         \n,A3,\n
1         \n,A3,\n
2         \n,A1,\n
3         \n,A1,\n
4         \n,A3,\n
           ...
62761    \n,S60,\n
62762    \n,S60,\n
62763    \n,S60,\n
62764    \n,S40,\n
62765    \n,S60,\n
Name: model, Length: 62766, dtype: object

In [21]:
df["model"]=df["model"].str.strip(',\n') 
df['model'] = df["model"].str.rstrip("['\\n' ,]")
df['model'] = df["model"].str.lstrip("[ '\\n' ]")


df["model"].head()

0    A3
1    A3
2    A1
3    A1
4    A3
Name: model, dtype: object

In [22]:
df["model"]=df["model"].str.replace("None","Others")

df["model"].head(20)

0     A3
1     A3
2     A1
3     A1
4     A3
5     A3
6     A1
7     A3
8     A1
9     A3
10    A3
11    A1
12    A5
13    A1
14    A5
15    A3
16    A3
17    A5
18    A3
19    A3
Name: model, dtype: object

# 4-short_description

In [23]:
df['short_description']

0                                2.0 FSI Ambition Pro Line
1        Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...
2          1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.
3        S-Line | Automaat | Navigatie | Cruise-/Climat...
4        Sportback 1.5 TFSI Sport | Dealer Onderhouden ...
                               ...
62761                            2.4 Edition APK/LMV/Airco
62762          2.4 Kinetic LPG-G3 NAP/LEER/NAVI/DAK/NW APK
62763    2.0T Edition,1e Eigenaar,LPG G3,Onderbouw,Navi...
62764                                                  2.4
62765        2.4 Airco, Cruise Control, Stuurbekrachtiging
Name: short_description, Length: 62766, dtype: object

In [24]:
df['short_description'].unique()

array(['2.0 FSI Ambition Pro Line',
       'Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmetaal//',
       '1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.', ...,
       '2.4 Kinetic LPG-G3 NAP/LEER/NAVI/DAK/NW APK',
       '2.0T Edition,1e Eigenaar,LPG G3,Onderbouw,Navi,Cli',
       '2.4 Airco, Cruise Control, Stuurbekrachtiging'], dtype=object)

In [25]:
df['short_description'].value_counts()

short_description
1.4 TSI Highline                                      58
i                                                     51
i High Executive                                      45
i Executive                                           41
High Executive                                        36
                                                      ..
110 CDI kort / rijklaar € 9450 ex btw / lease vana     1
210 2.2 CDI 366 HD L2 H2                               1
113 CDI 320 Lang Standaard / Airco / 3 Zits / Trek     1
109 CDI 90pk XL Lengte 2 L+R Schuifdeur                1
2.4 Airco, Cruise Control, Stuurbekrachtiging          1
Name: count, Length: 54368, dtype: int64

In [26]:
df['short_description']= df['short_description'].str.strip("\n,")
df['short_description'].value_counts()

short_description
1.4 TSI Highline                                      58
i                                                     51
i High Executive                                      45
i Executive                                           41
High Executive                                        36
                                                      ..
109 CDI | XL | Navigatie | Dubbele schuifdeur | De     1
110 CDI kort / rijklaar € 9450 ex btw / lease vana     1
210 2.2 CDI 366 HD L2 H2                               1
113 CDI 320 Lang Standaard / Airco / 3 Zits / Trek     1
2.4 Airco, Cruise Control, Stuurbekrachtiging          1
Name: count, Length: 54363, dtype: int64

# 5-price

In [27]:
# Include only numbers in the 'price' column
df['price'] = df['price'].replace({'[^0-9]': ''}, regex=True)

# Change empty data to NaN
df['price'] = df['price'].replace('', np.nan)

# Convert data to integer type
df['price'] = df['price'].astype('Int64')

In [28]:
df['price'].head()

0     4450
1    12950
2    12450
3    14945
4    24900
Name: price, dtype: Int64

In [29]:
df["price"].isna().sum()

1378

In [30]:
# delete null values
df = df.dropna(subset=["price"])

In [31]:
df["price"].head()

0     4450
1    12950
2    12450
3    14945
4    24900
Name: price, dtype: Int64

In [32]:
def find_column_outliers(df, column_name):
    column = df[column_name]
    Q1 = np.quantile(column, 0.25)
    Q3 = np.quantile(column, 0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - (1.5 * IQR)
    upper_limit = Q3 + (1.5 * IQR)
    
    outliers = column[(column < lower_limit) | (column > upper_limit)]
    return outliers

In [33]:


# find outliers
outliers = find_column_outliers(df, "price")

# print outliers
print(outliers)

# Convert 'price' column to 'float'
df['price'] = df['price'].astype('float')

# calculate upper limit after finding outliers
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - (1.5 * IQR)
upper_limit = Q3 + (1.5 * IQR)

# outlierları mean ile değiştiriyoruz
df.loc[df['price'] > upper_limit, 'price'] = df['price'].mean()

238       98350
239       69980
240      110250
241       69949
242       73800
          ...
62566     59950
62569     59900
62583     65900
62592     91500
62695    999999
Name: price, Length: 3586, dtype: Int64

# 6-mileage

In [34]:
df["mileage"]

0        ['', ['191,066 km']]
1         ['', ['94,758 km']]
2        ['', ['145,102 km']]
3        ['', ['119,666 km']]
4         ['', ['55,815 km']]
                 ...
62761    ['', ['298,160 km']]
62762    ['', ['442,713 km']]
62763    ['', ['340,257 km']]
62764    ['', ['399,990 km']]
62765    ['', ['404,758 km']]
Name: mileage, Length: 61388, dtype: object

In [35]:
df["mileage"].unique()

array(["['', ['191,066 km']]", "['', ['94,758 km']]",
       "['', ['145,102 km']]", ..., "['', ['340,257 km']]",
       "['', ['399,990 km']]", "['', ['404,758 km']]"], dtype=object)

In [36]:
df['mileage'] = df['mileage'].str.replace(',','')
df['mileage'] = df['mileage'].str.extract('(\d+)')
df["mileage"] = pd.to_numeric(df["mileage"], errors='coerce')
df["mileage"].fillna(df["mileage"].mean(), inplace=True) # Filled with mean
df["mileage"] = df["mileage"].astype(int)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\2111651334.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['mileage'] = df['mileage'].str.extract('(\d+)')
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\2111651334.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["mileage"].fillna(df["mileage"].mean(), inplace=True) # Filled with mean

In [37]:
df['mileage']

0        191066
1         94758
2        145102
3        119666
4         55815
          ...
62761    298160
62762    442713
62763    340257
62764    399990
62765    404758
Name: mileage, Length: 61388, dtype: int32

In [38]:
mileage_outliers = find_column_outliers(df,'mileage')
mileage_outliers

2083     390564
2095     499269
2482     496751
2614     490927
2655     424000
          ...
62753    385108
62756    448308
62762    442713
62764    399990
62765    404758
Name: mileage, Length: 503, dtype: int32

In [39]:


# Find outliers in 'mileage' column
mileage_outliers = find_column_outliers(df, 'mileage')

# Print outliers
print(mileage_outliers)

# Calculate mean of 'mileage' excluding outliers
mean_mileage = df.loc[~df['mileage'].isin(mileage_outliers), 'mileage'].mean()

# Fill outliers with the mean value
df.loc[df['mileage'].isin(mileage_outliers), 'mileage'] = mean_mileage

2083     390564
2095     499269
2482     496751
2614     490927
2655     424000
          ...
62753    385108
62756    448308
62762    442713
62764    399990
62765    404758
Name: mileage, Length: 503, dtype: int32

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3187289315.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '104133.03398209739' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[df['mileage'].isin(mileage_outliers), 'mileage'] = mean_mileage

# 7-gearbox  (there is also Gearbox) (we make a decision one of them)

In [40]:
df['gearbox'].value_counts()

gearbox
\n,Automatic,\n         35894
\n,Manual,\n            24800
\n,Semi-automatic,\n      603
['\n', None, '\n']         84
\n,02/2022,\n               2
\n,02/2020,\n               1
\n,08/2021,\n               1
\n,03/2014,\n               1
\n,09/2021,\n               1
\n,07/2017,\n               1
Name: count, dtype: int64

In [41]:
df['Gearbox'].value_counts()

Gearbox
\n,Automatic,\n         35899
\n,Manual,\n            24803
\n,Semi-automatic,\n      603
\n,None,\n                 83
Name: count, dtype: int64

In [42]:
# this one is the cleanest and useable.
df['Gearbox'] = df['Gearbox'].str.strip("\n ,")
df['Gearbox'] = df['Gearbox'].replace("['\n' None '\n']",np.nan)
df['Gearbox'].value_counts()

Gearbox
Automatic         35899
Manual            24803
Semi-automatic      603
None                 83
Name: count, dtype: int64

In [221]:
df.loc[df['gearbox'] != df['Gearbox'], ['gearbox', 'Gearbox']]
df.drop("gearbox", inplace=True, axis=1)

In [222]:
pd.set_option('display.max_columns', None)
df.head()

,location,make,model,short_description,price,mileage,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,country_version,offer_number,warranty,Mileage,first_registration,production_date,general_inspection,last_service,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,fuel_consumption,co2_emissions ( g/km),emission_class,emissions_sticker,comfort_convenience,entertainment_media,safety_security,extras,colour,paint,upholstery_colour,upholstery,warranty_category,full_service_encoded,non_smoker_encoded,fuel_cons_comb,fuel_cons_city,fuel_cons_country,air_conditioning,AppleCarPlay,abs_encoded
0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,08/2003,Gasoline,150,Dealer,Compact,Used,Front,5,3,None,SJ-112-R,6 months,"[['\n'], ['']]",08/2003,2003,05/2022,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1984,None,4,1280.000000,None,128,Euro 4,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, Radio]]","[[ABS, Alarm system, Central door lock, Centra...",[[Alloy wheels]],Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,None,NaN,NaN,1,[[CD player,0
1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,10/2013,Gasoline,125,Dealer,Compact,Used,Front,5,5,None,809725,None,"[['\n'], ['']]",10/2013,2013,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1200.000000,4.9 l/100 km (comb.),128,None,NoNonee,"[[Air conditioning, Automatic climate control,...","[[CD player, Radio]]","[[Alarm system, Central door lock, Central doo...","[[Alloy wheels (16"")]]",White,1,"upholstery, Black",Cloth,NaN,1,0,4.9,NaN,NaN,1,[[CD player,5
2,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,06/2015,Gasoline,125,Dealer,Compact,Used,None,5,5,Netherlands,2601307,6 months,"[['\n'], ['']]",06/2015,2015,01/2024,NaN,Yes,Yes,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1433.322061,"0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...",128,None,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[Bluetooth, CD player, On-board computer, USB]]","[[ABS, Central door lock with remote control, ...","[[Alloy wheels (15"")]]",Grey,0,NaN,NaN,1 year< :,1,1,0,0,0,1,[[Bluetooth,0
3,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,10/2015,Gasoline,125,Dealer,Compact,Used,Front,4,3,None,L-847-SK,6 months,"[['\n'], ['']]",10/2015,2015,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,7,4,1105.000000,"4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...",111,Euro 6,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, MP3, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Shift paddles, Sport sea...",Black,1,"upholstery, Black",Part leather,1 year< :,1,0,4.8,5.9,4.2,1,[[CD player,0
4,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,10/2017,Gasoline,150,Dealer,Compact,Used,Front,5,5,None,PZ-744-H,6 months,"[['\n'], ['']]",10/2017,2017,11/2023,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1495,7,4,1215.000000,"5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...",113,Euro 6,NoNonee,"[[Air conditioning, Armrest, Electrical side m...","[[CD player, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Sport seats, Sport suspe...",Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,5,6.2,4.3,1,[[CD player,0

# 8-registration

In [45]:
df['registration'].value_counts()

registration
01/2021    2857
01/2022    1282
12/2016     713
03/2021     709
12/2020     627
           ...
02/1981       1
05/1995       1
05/1999       1
07/2028       1
10/1996       1
Name: count, Length: 302, dtype: int64

In [46]:
df['registration'].isna().sum()

37

In [47]:
#filled nan value with 01/24
df['registration']=df['registration'].fillna('01/2024')
df['registration'].isna().sum()

0

# 10-fuel_type

In [48]:
#there is also Fuel_type !
df['Fuel_type'].value_counts()

Fuel_type
\n,Gasoline,\n                                        22377
\n,Super 95,\n                                        17309
\n,Diesel,\n                                          10527
\n,None,\n                                             8646
\n,Diesel (Particle filter),\n                         1197
\n,Super E10 95,\n                                      404
\n,LPG,\n                                               305
\n,Liquid petroleum gas (LPG),\n                        235
\n,Gasoline (Particle filter),\n                        140
\n,Electric,\n                                           73
\n,Domestic gas L,\n                                     54
\n,CNG,\n                                                40
\n,Super Plus 98,\n                                      27
\n,Super 95 (Particle filter),\n                         23
\n,Hydogen,\n                                            12
\n,Ethanol,\n                                             9
\n,Regular/Benzine 91,\n                                  4
\n,Others,\n                                              3
\n,Electric (Particle filter),\n                          1
\n,Domestic gas L (Particle filter),\n                    1
\n,Liquid petroleum gas (LPG) (Particle filter),\n        1
Name: count, dtype: int64

In [49]:
df['fuel_type'].value_counts()

fuel_type
\n,Gasoline,\n             36042
\n,Diesel,\n               11490
\n,Electric/Gasoline,\n     8062
\n,Electric,\n              4824
\n,LPG,\n                    541
\n,Electric/Diesel,\n        250
\n,CNG,\n                     95
\n,Hydrogen,\n                60
\n,Ethanol,\n                  9
\n,Others,\n                   7
\n,Automatic,\n                5
\n,Manual,\n                   3
Name: count, dtype: int64

In [50]:

df['Fuel_type'] = df['Fuel_type'].str.strip("\n\r,")
df['Fuel_type'].value_counts()

Fuel_type
Gasoline                                        22377
Super 95                                        17309
Diesel                                          10527
None                                             8646
Diesel (Particle filter)                         1197
Super E10 95                                      404
LPG                                               305
Liquid petroleum gas (LPG)                        235
Gasoline (Particle filter)                        140
Electric                                           73
Domestic gas L                                     54
CNG                                                40
Super Plus 98                                      27
Super 95 (Particle filter)                         23
Hydogen                                            12
Ethanol                                             9
Regular/Benzine 91                                  4
Others                                              3
Electric (Particle filter)                          1
Domestic gas L (Particle filter)                    1
Liquid petroleum gas (LPG) (Particle filter)        1
Name: count, dtype: int64

In [51]:
df['fuel_type'] = df['fuel_type'].str.strip("\n\r,")
df['fuel_type'].value_counts()

fuel_type
Gasoline             36042
Diesel               11490
Electric/Gasoline     8062
Electric              4824
LPG                    541
Electric/Diesel        250
CNG                     95
Hydrogen                60
Ethanol                  9
Others                   7
Automatic                5
Manual                   3
Name: count, dtype: int64

In [52]:
df.loc[(df['fuel_type'] == 'Automatic') | (df['fuel_type'] == 'Manual'),['fuel_type', 'Gearbox']] 
# those values are not belong to our "fuel_type" column therefore we checked other columns to see an opportunity

       fuel_type    Gearbox
15284     Manual     Manual
21624  Automatic  Automatic
29882     Manual     Manual
37355  Automatic  Automatic
37493     Manual     Manual
38045  Automatic  Automatic
55759  Automatic  Automatic
55764  Automatic  Automatic

In [53]:
df.loc[(df['fuel_type'] != df['Fuel_type']), ['fuel_type', 'Fuel_type']]

      fuel_type                   Fuel_type
0      Gasoline                    Super 95
4      Gasoline                    Super 95
5      Gasoline                    Super 95
9      Gasoline                    Super 95
11     Gasoline                    Super 95
...         ...                         ...
62755       LPG  Liquid petroleum gas (LPG)
62758       LPG  Liquid petroleum gas (LPG)
62759       LPG  Liquid petroleum gas (LPG)
62764       LPG  Liquid petroleum gas (LPG)
62765       LPG  Liquid petroleum gas (LPG)

[28283 rows x 2 columns]

"Fuel_type" column has more detailed information but too many None values. So we decided to keep "fuel_type" column and drop other

In [218]:
df.drop("Fuel_type", inplace=True, axis=1)

# Data Control

In [219]:
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,location,make,model,short_description,price,mileage,gearbox,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,country_version,offer_number,warranty,Mileage,first_registration,production_date,general_inspection,last_service,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,fuel_consumption,co2_emissions ( g/km),emission_class,emissions_sticker,comfort_convenience,entertainment_media,safety_security,extras,colour,paint,upholstery_colour,upholstery,warranty_category,full_service_encoded,non_smoker_encoded,fuel_cons_comb,fuel_cons_city,fuel_cons_country,air_conditioning,AppleCarPlay,abs_encoded
0,0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,"\n,Automatic,\n",08/2003,Gasoline,150,Dealer,Compact,Used,Front,5,3,None,SJ-112-R,6 months,"[['\n'], ['']]",08/2003,2003,05/2022,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1984,None,4,1280.000000,None,128,Euro 4,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, Radio]]","[[ABS, Alarm system, Central door lock, Centra...",[[Alloy wheels]],Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,None,NaN,NaN,1,[[CD player,0
1,1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,"\n,Automatic,\n",10/2013,Gasoline,125,Dealer,Compact,Used,Front,5,5,None,809725,None,"[['\n'], ['']]",10/2013,2013,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1200.000000,4.9 l/100 km (comb.),128,None,NoNonee,"[[Air conditioning, Automatic climate control,...","[[CD player, Radio]]","[[Alarm system, Central door lock, Central doo...","[[Alloy wheels (16"")]]",White,1,"upholstery, Black",Cloth,NaN,1,0,4.9,NaN,NaN,1,[[CD player,5
2,3,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,"\n,Automatic,\n",06/2015,Gasoline,125,Dealer,Compact,Used,None,5,5,Netherlands,2601307,6 months,"[['\n'], ['']]",06/2015,2015,01/2024,NaN,Yes,Yes,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1433.322061,"0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...",128,None,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[Bluetooth, CD player, On-board computer, USB]]","[[ABS, Central door lock with remote control, ...","[[Alloy wheels (15"")]]",Grey,0,NaN,NaN,1 year< :,1,1,0,0,0,1,[[Bluetooth,0
3,4,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,"\n,Automatic,\n",10/2015,Gasoline,125,Dealer,Compact,Used,Front,4,3,None,L-847-SK,6 months,"[['\n'], ['']]",10/2015,2015,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,7,4,1105.000000,"4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...",111,Euro 6,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, MP3, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Shift paddles, Sport sea...",Black,1,"upholstery, Black",Part leather,1 year< :,1,0,4.8,5.9,4.2,1,[[CD player,0
4,7,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,"\n,Automatic,\n",10/2017,Gasoline,150,Dealer,Compact,Used,Front,5,5,None,PZ-744-H,6 months,"[['\n'], ['']]",10/2017,2017,11/2023,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1495,7,4,1215.000000,"5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...",113,Euro 6,NoNonee,"[[Air conditioning, Armrest, Electrical side m...","[[CD player, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Sport seats, Sport suspe...",Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,5,6.2,4.3,1,[[CD player,0

# 11-power

In [56]:
#'registration' has 7 "power" values
case_1 = ~df['registration'].str.match(r'\d{2}/\d{4}') # All values that is not in given format
case_1.value_counts()

registration
False    61381
True         7
Name: count, dtype: int64

In [57]:
df.loc[case_1, ['power', 'registration']]  # Corresponding values of case_1 in "power" column. We see "registiration" column has "power" values

            power     registration
15284   3,500 kg,   96 kW (131 hp)
29882   2,159 kg,   75 kW (102 hp)
37355   2,735 kg,  130 kW (177 hp)
37493   1,588 kg,   90 kW (122 hp)
38045  [None, '']  265 kW (360 hp)
55759  [None, '']   96 kW (131 hp)
55764  [None, '']   96 kW (131 hp)

In [58]:
df.loc[case_1, 'power'] = None   # Clear the rows
df.loc[case_1, ['power', 'registration']] = df.loc[case_1,'registration'].apply(str) #writes values in "power" column
df.loc[case_1, ['power', 'registration']]

                 power     registration
15284   96 kW (131 hp)   96 kW (131 hp)
29882   75 kW (102 hp)   75 kW (102 hp)
37355  130 kW (177 hp)  130 kW (177 hp)
37493   90 kW (122 hp)   90 kW (122 hp)
38045  265 kW (360 hp)  265 kW (360 hp)
55759   96 kW (131 hp)   96 kW (131 hp)
55764   96 kW (131 hp)   96 kW (131 hp)

In [59]:
df["power"] = df["power"].str.extract("(\d+)(?=\D*$)")
df["power"] = pd.to_numeric(df['power'], errors='coerce')
df['power'] = df['power'].replace(np.nan,df['power'].mean())
df['power'] = df["power"].astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\4042744926.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["power"] = df["power"].str.extract("(\d+)(?=\D*$)")

In [60]:
df["power"].isna().sum()

0

In [61]:
power_outliers = find_column_outliers(df,'power')
power_outliers

15       265
51       265
104      260
115      300
133      271
        ...
62699    305
62700    286
62702    315
62704    286
62705    272
Name: power, Length: 5308, dtype: int32

In [249]:
df.rename(columns={'power': 'power (hp)'}, inplace=True)

# 12-seller

In [62]:
df['seller']
df['seller'].unique()

array(["['\\n', ['Dealer\\n']]", "['\\n', ['Private seller\\n']]",
       "['\\n', ['Diesel\\n']]", "['\\n', ['Electric\\n']]",
       "['\\n', ['Gasoline\\n']]"], dtype=object)

In [63]:
df['seller'] = df['seller'].str.lstrip("[', [' \s\S\t n ")
df['seller'] = df['seller'].str.rstrip("[', [] ' \s\S\t n")  


#burada Dizel elektrik ve gasonilne bu sütuna ait değil
df["seller"].replace("Diesel", None, inplace = True) 
df["seller"].replace("Electric", None, inplace = True) 
df["seller"].replace("Gasoline", None, inplace = True) 
df["seller"].value_counts()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\434807809.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['seller'] = df['seller'].str.lstrip("[', [' \s\S\t n ")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\434807809.py:2: SyntaxWarning: invalid escape sequence '\s'
  df['seller'] = df['seller'].str.rstrip("[', [] ' \s\S\t n")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\434807809.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["seller"].replace("Diesel", None, inplace = True)
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\434807809.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["seller"].replace("Electric", None, inplace = True)
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\434807809.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["seller"].replace("Gasoline", None, inplace = True)

seller
Dealer            56050
Private seller     5330
Name: count, dtype: int64

# 13-body_type

In [64]:
df['body_type']

0        \n,Compact,\n
1        \n,Compact,\n
2        \n,Compact,\n
3        \n,Compact,\n
4        \n,Compact,\n
             ...
62761      \n,Sedan,\n
62762      \n,Sedan,\n
62763      \n,Sedan,\n
62764      \n,Sedan,\n
62765      \n,Sedan,\n
Name: body_type, Length: 61388, dtype: object

In [65]:
df['body_type'] .unique()

array(['\n,Compact,\n', '\n,None,\n', '\n,Convertible,\n', '\n,Coupe,\n',
       '\n,Off-Road/Pick-up,\n', '\n,Station wagon,\n', '\n,Sedan,\n',
       '\n,Other,\n', '\n,Van,\n', '\n,Transporter,\n', '\n,Panel van,\n',
       '\n,Car transport,\n', '\n,Flatbed van,\n'], dtype=object)

In [66]:
df['body_type'].value_counts() #948 none değer var.

body_type
\n,Off-Road/Pick-up,\n    17059
\n,Compact,\n             12894
\n,Station wagon,\n       11038
\n,Van,\n                  6085
\n,Sedan,\n                5216
\n,Convertible,\n          3531
\n,Transporter,\n          2203
\n,Coupe,\n                1861
\n,None,\n                  948
\n,Other,\n                 549
\n,Panel van,\n               2
\n,Car transport,\n           1
\n,Flatbed van,\n             1
Name: count, dtype: int64

In [67]:
df['body_type'] = df['body_type'].str.replace(',', '').str.strip()

In [68]:
df['body_type'] = df['body_type'].str.replace('None', 'Other')
df['body_type'].value_counts() #none 'ları otherlara ekledik

body_type
Off-Road/Pick-up    17059
Compact             12894
Station wagon       11038
Van                  6085
Sedan                5216
Convertible          3531
Transporter          2203
Coupe                1861
Other                1497
Panel van               2
Car transport           1
Flatbed van             1
Name: count, dtype: int64

# 14--type

In [69]:
df['type'].unique()

array(['\n,Used,\n', '\n,None,\n', '\n,Demonstration,\n',
       '\n,Pre-registered,\n', '\n,New,\n'], dtype=object)

In [70]:
df['type'].value_counts() #none değerler var 948.

type
\n,Used,\n              54275
\n,New,\n                3399
\n,Demonstration,\n      1792
\n,Pre-registered,\n      974
\n,None,\n                948
Name: count, dtype: int64

In [71]:
df['type'] = df['type'].str.replace(',', '').str.strip()

In [72]:
df['type'].value_counts()

type
Used              54275
New                3399
Demonstration      1792
Pre-registered      974
None                948
Name: count, dtype: int64

In [259]:
df['type'] = df['type'].replace('None', 'No Info')

In [260]:
df['type'].value_counts()

type
Used              54275
New                3399
Demonstration      1792
Pre-registered      974
No Info             948
Name: count, dtype: int64

# 15-drivetrain

In [74]:
df['drivetrain'].unique()

array(['\n,Front,\n', '\n,None,\n', '\n,4WD,\n', '\n,Rear,\n'],
      dtype=object)

In [75]:
df['drivetrain'] = df['drivetrain'].str.replace(',', '').str.strip()
df['drivetrain'].value_counts()

drivetrain
Front    32765
None     14325
4WD       7197
Rear      7101
Name: count, dtype: int64

In [256]:
mode_value = df['drivetrain'].mode()[0]
df['drivetrain'].replace('No Info', mode_value, inplace=True)

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\1128565988.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['drivetrain'].replace('No Info', mode_value, inplace=True)

In [257]:
df['drivetrain'].value_counts()

drivetrain
Front    47090
4WD       7197
Rear      7101
Name: count, dtype: int64

In [258]:
# burada 14325 none değeri mode ile doldurduk

# 16-seats

In [77]:
df["seats"].unique()

array(['\n5', '\n4', 'None\n', '\n2', '\n6', '\n7', '\n3', '\n14', '\n9',
       '\n8', '\n1'], dtype=object)

In [78]:
df["seats"]=df["seats"].str.strip(',\n')
df["seats"].value_counts()

seats
5       45667
4        5881
None     4841
2        1954
7        1800
3         878
6         254
8          56
9          54
1           2
14          1
Name: count, dtype: int64

In [79]:
most_common_value = df['seats'].mode()[0]
df['seats'] = df['seats'].replace('None', most_common_value)
# mod ile en cok olana eşitledik none ları

In [80]:
df["seats"].value_counts()

seats
5     50508
4      5881
2      1954
7      1800
3       878
6       254
8        56
9        54
1         2
14        1
Name: count, dtype: int64

In [81]:
df["seats"].isna().sum()

0

# 17-doors

In [82]:
df["doors"].unique()

array(['\n3', '\n5', '\n4', 'None\n', '\n2', '\n6', '\n1'], dtype=object)

In [83]:
df["doors"].value_counts() # none değer var 1160

doors
\n5       44516
\n4        8244
\n2        5133
\n3        2254
None\n     1160
\n6          79
\n1           2
Name: count, dtype: int64

In [84]:

df["doors"]=df["doors"].str.strip(',\n')

In [85]:
df["doors"].replace("None", np.nan) 
df["doors"].head()

0    3
1    5
2    5
3    3
4    5
Name: doors, dtype: object

In [86]:


df["doors"].isna().sum()

0

In [87]:
df["doors"].head()

0    3
1    5
2    5
3    3
4    5
Name: doors, dtype: object

In [88]:
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,location,make,model,short_description,price,mileage,gearbox,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,country_version,offer_number,warranty,Mileage,first_registration,production_date,general_inspection,last_service,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,Fuel_type,fuel_consumption,co2_emissions,emission_class,emissions_sticker,\nComfort & Convenience\n,\nEntertainment & Media\n,\nSafety & Security\n,extras,\ncolour,\nmanufacturer_color,\npaint,upholstery_colour,upholstery
0,0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,"\n,Automatic,\n",08/2003,Gasoline,150,Dealer,Compact,Used,Front,5,3,"Country version,None",\nSJ-112-R,"\n,6 months,\n","[['\n'], ['']]",08/2003,NaN,05/2022,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,110 kW (150 hp),\n",Automatic,"\n,1,984 cc,\n","\n,None,\n","\n,4,\n","\n,1,280 kg,\n",Super 95,"\n,None,\n","['\n', [' ', ' ', ' '], '\n']","\n,Euro 4,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'Radio']]","[['ABS', 'Alarm system', 'Central door lock', ...",[['Alloy wheels']],"\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth"
1,1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,"\n,Automatic,\n",10/2013,Gasoline,125,Dealer,Compact,Used,Front,5,5,"Country version,None",\n809725,"\n,None,\n","[['\n'], ['']]",10/2013,NaN,NaN,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n",Automatic,"\n,1,395 cc,\n","\n,None,\n","\n,4,\n","\n,1,200 kg,\n",Gasoline,"['\n', ['4.9 l/100 km (comb.)', ' ', ' '], '\n']","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Automatic climate contr...","[['CD player', 'Radio']]","[['Alarm system', 'Central door lock', 'Centra...","[['Alloy wheels (16"")']]","\n4, White",NaN,NaN,"\nupholstery, Black","\n8, Cloth"
2,3,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,"\n,Automatic,\n",06/2015,Gasoline,125,Dealer,Compact,Used,None,5,5,"Country version,Netherlands",\n2601307,"\n,6 months,\n","[['\n'], ['']]",06/2015,2015.0,New,NaN,"\n,Yes,\n","\n,Yes,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n",Automatic,"\n,1,395 cc,\n","\n,None,\n","\n,4,\n","\n,None,\n",Gasoline,"['\n', ['0 l/100 km (comb.)', '0 l/100 km (cit...","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['Bluetooth', 'CD player', 'On-board computer...","[['ABS', 'Central door lock with remote contro...","[['Alloy wheels (15"")']]","\n4, Grey",NaN,"\npaint, Metallic",NaN,NaN
3,4,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,"\n,Automatic,\n",10/2015,Gasoline,125,Dealer,Compact,Used,Front,4,3,"Country version,None",\nL-847-SK,"\n,6 months,\n","[['\n'], ['']]",10/2015,NaN,NaN,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,92 kW (125 hp),\n",Automatic,"\n,1,395 cc,\n","\n,7,\n","\n,4,\n","\n,1,105 kg,\n",Gasoline,"['\n', ['4.8 l/100 km (comb.)', '5.9 l/100 km ...","\n,111 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'MP3', 'On-board computer', 'Ra...","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Shift paddles', 'Spor...","\n4, Black",NaN,NaN,"\nupholstery, Black","\n8, Part leather"
4,7,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,"\n,Automatic,\n",10/2017,Gasoline,150,Dealer,Compact,Used,Front,5,5,"Country version,None",\nPZ-744-H,"\n,6 months,\n","[['\n'], ['']]",10/2017,NaN,11/2023,NaN,"\n,Yes,\n","\n,None,\n","[['\n'], ['None']]","[['\n'], ['None']]","\n,110 kW (150 hp),\n",Automatic,"\n,1,495 cc,\n","\n,7,\n","\n,4,\n","\n,1,215 kg,\n",Super 95,"['\n', ['5 l/100 km (comb.)', '6.2 l/100 km (c...","\n,113 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Electrical s...","[['CD player', 'On-board computer', 'Radio']]","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Sport seats', 'Sport ...","\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth"

# 18-country_version

In [89]:
df['country_version'].value_counts() # 53650 None değer var

country_version
Country version,None                    53650
Country version,Netherlands              6665
Country version,Germany                   747
Country version,Belgium                   102
Country version,Sweden                     50
Country version,Denmark                    36
Country version,Czechia                    19
Country version,France                     19
Country version,Spain                      16
Country version,Italy                      13
Country version,United States              13
Country version,Switzerland                13
Country version,Poland                     12
Country version,Austria                     9
Country version,Luxembourg                  6
Country version,Slovenia                    4
Country version,Japan                       2
Country version,Canada                      2
Country version,United Kingdom              2
Country version,Hungary                     2
Country version,Latvia                      1
Country version,Romania                     1
Country version,Estonia                     1
Country version,Namibia                     1
Country version,Lithuania                   1
Country version,United Arab Emirates        1
Name: count, dtype: int64

In [90]:
df['country_version'] = df['country_version'].str.split(',').str[-1].str.strip()

In [91]:
#burada ne yapmamız gerekiyor?

In [223]:
df.drop("country_version", inplace=True, axis=1)   #opsiyonlardan biri silmek

# 19-offer_number

In [93]:
df["offer_number"].unique()

array(['\nSJ-112-R', '\n809725', '\n2601307', ..., '\n06-RB-XS',
       '\n75-PK-RN', '\n26-HN-LS'], dtype=object)

In [94]:
df["offer_number"].value_counts()

offer_number
None\n        9867
\nNIEUW         53
\nXX            28
\n.             17
\n1776          13
              ...
\nN-652-PX       1
\n7157           1
\n30035574       1
\n#37766         1
\n26-HN-LS       1
Name: count, Length: 48890, dtype: int64

In [95]:
df["offer_number"]= df["offer_number"].str.strip(',\n')
df["offer_number"].value_counts() #9867 none değer var, ne yapılabilir ?

offer_number
None        9867
NIEUW         53
XX            28
.             17
1776          13
            ...
N-652-PX       1
7157           1
30035574       1
#37766         1
26-HN-LS       1
Name: count, Length: 48890, dtype: int64

In [224]:
df.drop("offer_number", inplace=True, axis=1) #opsiyonlardan biri

# 20-warranty

In [97]:
df['warranty'].unique()

array(['\n,6 months,\n', '\n,None,\n', '\n,3 months,\n', '\n,1 months,\n',
       '\n,12 months,\n', '\n,60 months,\n', '\n,26 months,\n',
       '\n,24 months,\n', '\n,18 months,\n', '\n,36 months,\n',
       '\n,48 months,\n', '\n,2 months,\n', '\n,9 months,\n',
       '\n,10 months,\n', '\n,Yes,\n', '\n,84 months,\n',
       '\n,4 months,\n'], dtype=object)

In [98]:
df['warranty'].value_counts()

warranty
\n,None,\n         40661
\n,6 months,\n     16282
\n,3 months,\n      1602
\n,12 months,\n     1336
\n,24 months,\n     1007
\n,1 months,\n       235
\n,84 months,\n      204
\n,18 months,\n       29
\n,36 months,\n        8
\n,48 months,\n        6
\n,2 months,\n         6
\n,Yes,\n              3
\n,60 months,\n        3
\n,26 months,\n        2
\n,9 months,\n         2
\n,10 months,\n        1
\n,4 months,\n         1
Name: count, dtype: int64

In [99]:
df['warranty'] = df['warranty'].str.replace(',', '').str.strip()
df['warranty'].value_counts()   #40661 none değer var burada garanti var yok şeklinde yapılabilir.

warranty
None         40661
6 months     16282
3 months      1602
12 months     1336
24 months     1007
1 months       235
84 months      204
18 months       29
36 months        8
48 months        6
2 months         6
Yes              3
60 months        3
26 months        2
9 months         2
10 months        1
4 months         1
Name: count, dtype: int64

In [100]:
#burada 3 tane yes değeri 1 veya daha az garantiye aldık. diğerlerini kategorileştirdik
category1 = ['1 months', '2 months', '4 months', '3 months', '6 months', '9 months', '10 months', '12 months',  'Yes']
category2 = ['18 months', '24 months','26 months', '36 months', '48 months', '60 months']
category3 = ['84 months']


df['warranty_category'] = pd.cut(pd.to_numeric(df['warranty'].str.extract('(\d+)', expand=False)), 
                                  bins=[0, 13, 60, 1000], 
                                  labels=['1 year<    :', '2-5 year    :', '5+ years:'])

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\4107282813.py:7: SyntaxWarning: invalid escape sequence '\d'
  df['warranty_category'] = pd.cut(pd.to_numeric(df['warranty'].str.extract('(\d+)', expand=False)),

In [101]:
df['warranty_category'].value_counts()

warranty_category
1 year<    :     19465
2-5 year    :     1055
5+ years:          204
Name: count, dtype: int64

# 21-Mileage

In [102]:
df['Mileage'].unique()

array(["[['\\n'], ['']]", "[['\\n'], ['None']]"], dtype=object)

In [103]:
df['Mileage'].value_counts()

Mileage
[['\n'], ['']]        61255
[['\n'], ['None']]      133
Name: count, dtype: int64

In [104]:
df['mileage'].value_counts() #mileage sütunu iki tane ilk sütun daha anlamlı

mileage
10.000000        1355
1.000000         1020
5.000000          723
15.000000         676
104133.033982     503
                 ...
72499.000000        1
105772.000000       1
87283.000000        1
63758.000000        1
340257.000000       1
Name: count, Length: 44162, dtype: int64

In [225]:
df.drop("Mileage", inplace=True, axis=1)

# 22-First_registration

In [106]:
df['first_registration'].value_counts()

first_registration
01/2021    2857
01/2022    1282
12/2016     713
03/2021     709
12/2020     627
           ...
04/1997       1
07/1998       1
04/1999       1
05/1997       1
10/1996       1
Name: count, Length: 297, dtype: int64

In [107]:
df['registration'].value_counts # bu sütun daha anlamlı ve ikisi de aynı anlamları ifade ettiği için 22.sütun silinebilirr

<bound method IndexOpsMixin.value_counts of 0        08/2003
1        10/2013
2        06/2015
3        10/2015
4        10/2017
          ...
62761    12/2000
62762    02/2005
62763    08/2004
62764    01/2004
62765    09/2001
Name: registration, Length: 61388, dtype: object>

In [242]:
df.drop('first_registration',inplace=True, axis=1)

# 23-production_date

In [108]:
df['production_date'].value_counts()

production_date
2021.0    976
2017.0    615
2016.0    522
2020.0    494
2018.0    469
2019.0    378
2015.0    310
2014.0    302
2011.0    285
2013.0    264
2012.0    244
2010.0    228
2008.0    189
2009.0    178
2022.0    170
2007.0    152
2005.0    135
2006.0    135
2004.0    107
2003.0     80
2002.0     67
2001.0     48
2000.0     36
1998.0      2
1997.0      1
Name: count, dtype: int64

In [109]:


# Fill NaN values in 'production_date' with the corresponding values from 'registration'
df['production_date'] = np.where(df['production_date'].isnull(), df['registration'].str.split('/').str[1], df['production_date'])

In [110]:
df_origin.loc[df_origin['production_date'].isna(), ['production_date', 'registration']] #Nan değerleri kontrol ediyoruz

       production_date registration
0                  NaN      08/2003
1                  NaN      10/2013
3                  NaN      10/2015
4                  NaN      10/2017
5                  NaN      03/2019
...                ...          ...
62761              NaN      12/2000
62762              NaN      02/2005
62763              NaN      08/2004
62764              NaN      01/2004
62765              NaN      09/2001

[56210 rows x 2 columns]

In [111]:
df_origin.loc[(df_origin['production_date'] == "None"), ['production_date', 'registration']]

Empty DataFrame
Columns: [production_date, registration]
Index: []

In [112]:
df[ ['production_date', 'registration']]

      production_date registration
0                2003      08/2003
1                2013      10/2013
2              2015.0      06/2015
3                2015      10/2015
4                2017      10/2017
...               ...          ...
62761            2000      12/2000
62762            2005      02/2005
62763            2004      08/2004
62764            2004      01/2004
62765            2001      09/2001

[61388 rows x 2 columns]

In [113]:
df["production_date"].unique()

array(['2003', '2013', 2015.0, '2015', '2017', '2019', '2014', 2011.0,
       2012.0, '2011', '2012', '2010', 2013.0, '2016', 2016.0, 2014.0,
       '2009', 2010.0, '2005', '2004', '2008', 2009.0, '2018', '2021',
       2021.0, '2002', 2004.0, '2006', 2017.0, '2020', '2007', '2000',
       '2001', 2008.0, 2006.0, 2007.0, 2020.0, 2018.0, 2003.0, 2000.0,
       2019.0, '2022', '1999', 2005.0, '2028', 2001.0, 2002.0, '1995',
       2022.0, '2024', nan, '1981', '1997', 1998.0, '1998', '1976',
       '1993', 1997.0, '1991', '1994', '1996'], dtype=object)

In [114]:
df['production_date'] = df['production_date'].astype(str)

# Ardından ondalık kısmı kaldıralım
df['production_date'] = df['production_date'].str.split('.').str[0]

# Son olarak, eksik değerlerin nasıl ele alınacağını belirleyelim. Burada 'NaN' değerlerini 'Bilinmiyor' olarak değiştiriyorum.
df['production_date'].replace('nan', 'None', inplace=True)

# 'production_date' sütunundaki 'None' değerlerini 'registration' sütunundaki değerlerle dolduruyoruz
df['production_date'] = df.apply(lambda row: row['registration'] if row['production_date'] == 'None' else row['production_date'], axis=1)

# Düzenlenmiş DataFrame'i yazdıralım
df["production_date"].unique()

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\282976703.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['production_date'].replace('nan', 'None', inplace=True)

array(['2003', '2013', '2015', '2017', '2019', '2014', '2011', '2012',
       '2010', '2016', '2009', '2005', '2004', '2008', '2018', '2021',
       '2002', '2006', '2020', '2007', '2000', '2001', '2022', '1999',
       '2028', '1995', '2024', '96 kW (131 hp)', '1981', '1997', '1998',
       '75 kW (102 hp)', '130 kW (177 hp)', '1976', '1993', '1991',
       '1994', '1996'], dtype=object)

In [115]:
# 'Power' sütunundaki üç unique değeri 'production_date' sütunundaki satırlarla yer değiştiriyoruz
df.loc[df['production_date'] == '96 kW (131 hp)', 'Power'] = '96 kW (131 hp)'
df.loc[df['production_date'] == '75 kW (102 hp)', 'Power'] = '75 kW (102 hp)'
df.loc[df['production_date'] == '130 kW (177 hp)', 'Power'] = '130 kW (177 hp)'

# 'production_date' sütunundaki ilgili satırları boş olarak ayarlıyoruz
df.loc[df['production_date'].isin(['96 kW (131 hp)', '75 kW (102 hp)', '130 kW (177 hp)']), 'production_date'] = None

# Sonuçları yazdırıyoruz
print(df["production_date"].unique())

['2003' '2013' '2015' '2017' '2019' '2014' '2011' '2012' '2010' '2016'
 '2009' '2005' '2004' '2008' '2018' '2021' '2002' '2006' '2020' '2007'
 '2000' '2001' '2022' '1999' '2028' '1995' '2024' None '1981' '1997'
 '1998' '1976' '1993' '1991' '1994' '1996']

In [116]:
df["production_date"].value_counts()

production_date
2021    8056
2017    5491
2016    5062
2018    4195
2020    4124
2015    3444
2019    3145
2014    2809
2011    2799
2013    2799
2012    2778
2010    2546
2008    2086
2009    2080
2007    1751
2006    1521
2005    1450
2022    1437
2004    1231
2003     966
2002     700
2001     494
2000     358
2024      34
1997       6
1999       5
1998       5
1995       2
1993       2
1994       2
2028       1
1981       1
1976       1
1991       1
1996       1
Name: count, dtype: int64

# 24-general_inspection

In [117]:
df['general_inspection'].unique()

array(['05/2022', nan, 'New', '11/2023', '07/2022', '12/2022', '06/2022',
       '08/2022', '04/2022', '01/2022', '02/2023', '03/2022', '05/2023',
       '10/2022', '07/2023', '11/2022', '01/2023', '06/2023', '09/2022',
       '04/2023', '02/2022', '10/2023', '02/2025', '08/2023', '09/2021',
       '11/2021', '05/2025', '02/2024', '09/2023', '05/2024', '06/2024',
       '10/2021', '03/2025', '06/2025', '03/2023', '07/2024', '09/2024',
       '04/2025', '04/2024', '03/2024', '01/2024', '12/2023', '05/2021',
       '12/2024', '10/2025', '09/2025', '08/2025', '10/2024', '08/2021',
       '12/2021', '11/2020', '07/2021', '09/2020', '12/2020', '06/2019',
       '11/2024', '08/2024', '08/2018', '11/2025', '12/2025', '07/2025',
       '01/2025', '01/2026', '04/2021', '01/2021', '09/2017', '02/2021',
       '06/2021', '03/2020', '11/2014', '11/2019', '08/2020', '04/2026',
       '09/2019', '01/2020', '07/2020', '07/2019', '11/2017', '12/2016',
       '06/2020', '03/2021', '10/2020', '11/2016', '11/2026', '07/2026',
       '02/2026', '02/2015', '06/2026', '04/2019', '05/2026', '02/2020',
       '03/2019', '09/2018', '12/2019'], dtype=object)

In [118]:
df['general_inspection'] = df['general_inspection'].str.replace('New', '01/2024')

df["general_inspection"].value_counts()

general_inspection
01/2024    15434
06/2022     2114
03/2022     1964
05/2022     1889
07/2022     1887
           ...
08/2018        1
11/2019        1
11/2014        1
09/2017        1
12/2019        1
Name: count, Length: 92, dtype: int64

In [119]:
df["general_inspection"].unique()

array(['05/2022', nan, '01/2024', '11/2023', '07/2022', '12/2022',
       '06/2022', '08/2022', '04/2022', '01/2022', '02/2023', '03/2022',
       '05/2023', '10/2022', '07/2023', '11/2022', '01/2023', '06/2023',
       '09/2022', '04/2023', '02/2022', '10/2023', '02/2025', '08/2023',
       '09/2021', '11/2021', '05/2025', '02/2024', '09/2023', '05/2024',
       '06/2024', '10/2021', '03/2025', '06/2025', '03/2023', '07/2024',
       '09/2024', '04/2025', '04/2024', '03/2024', '12/2023', '05/2021',
       '12/2024', '10/2025', '09/2025', '08/2025', '10/2024', '08/2021',
       '12/2021', '11/2020', '07/2021', '09/2020', '12/2020', '06/2019',
       '11/2024', '08/2024', '08/2018', '11/2025', '12/2025', '07/2025',
       '01/2025', '01/2026', '04/2021', '01/2021', '09/2017', '02/2021',
       '06/2021', '03/2020', '11/2014', '11/2019', '08/2020', '04/2026',
       '09/2019', '01/2020', '07/2020', '07/2019', '11/2017', '12/2016',
       '06/2020', '03/2021', '10/2020', '11/2016', '11/2026', '07/2026',
       '02/2026', '02/2015', '06/2026', '04/2019', '05/2026', '02/2020',
       '03/2019', '09/2018', '12/2019'], dtype=object)

In [120]:

#bunu tekrar yap!

In [121]:
df["general_inspection"].unique()

array(['05/2022', nan, '01/2024', '11/2023', '07/2022', '12/2022',
       '06/2022', '08/2022', '04/2022', '01/2022', '02/2023', '03/2022',
       '05/2023', '10/2022', '07/2023', '11/2022', '01/2023', '06/2023',
       '09/2022', '04/2023', '02/2022', '10/2023', '02/2025', '08/2023',
       '09/2021', '11/2021', '05/2025', '02/2024', '09/2023', '05/2024',
       '06/2024', '10/2021', '03/2025', '06/2025', '03/2023', '07/2024',
       '09/2024', '04/2025', '04/2024', '03/2024', '12/2023', '05/2021',
       '12/2024', '10/2025', '09/2025', '08/2025', '10/2024', '08/2021',
       '12/2021', '11/2020', '07/2021', '09/2020', '12/2020', '06/2019',
       '11/2024', '08/2024', '08/2018', '11/2025', '12/2025', '07/2025',
       '01/2025', '01/2026', '04/2021', '01/2021', '09/2017', '02/2021',
       '06/2021', '03/2020', '11/2014', '11/2019', '08/2020', '04/2026',
       '09/2019', '01/2020', '07/2020', '07/2019', '11/2017', '12/2016',
       '06/2020', '03/2021', '10/2020', '11/2016', '11/2026', '07/2026',
       '02/2026', '02/2015', '06/2026', '04/2019', '05/2026', '02/2020',
       '03/2019', '09/2018', '12/2019'], dtype=object)

In [245]:
df['general_inspection'] = pd.to_datetime(df['general_inspection'], errors='coerce')

# Filter out dates after January 2024
mask = df['general_inspection'] > pd.Timestamp('2024-01-01')
df.loc[mask, 'general_inspection'] = pd.Timestamp('2024-01-01')

# Convert datetime back to string format 'mm/yyyy'
df['general_inspection'] = df['general_inspection'].dt.strftime('%m/%Y')

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3083694754.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['general_inspection'] = pd.to_datetime(df['general_inspection'], errors='coerce')

In [246]:
df["general_inspection"].unique()

array(['05/2022', nan, '01/2024', '11/2023', '07/2022', '12/2022',
       '06/2022', '08/2022', '04/2022', '01/2022', '02/2023', '03/2022',
       '05/2023', '10/2022', '07/2023', '11/2022', '01/2023', '06/2023',
       '09/2022', '04/2023', '02/2022', '10/2023', '08/2023', '09/2021',
       '11/2021', '09/2023', '10/2021', '03/2023', '12/2023', '05/2021',
       '08/2021', '12/2021', '11/2020', '07/2021', '09/2020', '12/2020',
       '06/2019', '08/2018', '04/2021', '01/2021', '09/2017', '02/2021',
       '06/2021', '03/2020', '11/2014', '11/2019', '08/2020', '09/2019',
       '01/2020', '07/2020', '07/2019', '11/2017', '12/2016', '06/2020',
       '03/2021', '10/2020', '11/2016', '02/2015', '04/2019', '02/2020',
       '03/2019', '09/2018', '12/2019'], dtype=object)

In [247]:
# Fill NaN values with the mode
mode_value = df['general_inspection'].mode()[0]  # Calculate the mode
df['general_inspection'].fillna(mode_value, inplace=True)

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\2721187545.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['general_inspection'].fillna(mode_value, inplace=True)

In [248]:
df["general_inspection"].unique()

array(['05/2022', '01/2024', '11/2023', '07/2022', '12/2022', '06/2022',
       '08/2022', '04/2022', '01/2022', '02/2023', '03/2022', '05/2023',
       '10/2022', '07/2023', '11/2022', '01/2023', '06/2023', '09/2022',
       '04/2023', '02/2022', '10/2023', '08/2023', '09/2021', '11/2021',
       '09/2023', '10/2021', '03/2023', '12/2023', '05/2021', '08/2021',
       '12/2021', '11/2020', '07/2021', '09/2020', '12/2020', '06/2019',
       '08/2018', '04/2021', '01/2021', '09/2017', '02/2021', '06/2021',
       '03/2020', '11/2014', '11/2019', '08/2020', '09/2019', '01/2020',
       '07/2020', '07/2019', '11/2017', '12/2016', '06/2020', '03/2021',
       '10/2020', '11/2016', '02/2015', '04/2019', '02/2020', '03/2019',
       '09/2018', '12/2019'], dtype=object)

# 25-last_service

In [122]:
df['last_service'].unique() #column only has nan value. Drop done.

array([nan])

In [226]:
df.drop("last_service", inplace=True, axis=1)

# 26-full_service_history --changed to 0 and 1.

In [124]:
df['full_service_history'].value_counts()

full_service_history
\n,Yes,\n     42057
\n,None,\n    19331
Name: count, dtype: int64

In [125]:
df['full_service_history'] = df['full_service_history'].str.replace(',', '').str.strip()
df['full_service_history'].value_counts()

full_service_history
Yes     42057
None    19331
Name: count, dtype: int64

In [126]:
from sklearn.preprocessing import LabelEncoder          
lbe=LabelEncoder()
lbe.fit_transform(df["full_service_history"])

df['full_service_encoded']=lbe.fit_transform(df["full_service_history"])
df['full_service_encoded']

0        1
1        1
2        1
3        1
4        1
        ..
62761    1
62762    1
62763    1
62764    0
62765    0
Name: full_service_encoded, Length: 61388, dtype: int32

# Data Check

In [227]:
pd.set_option('display.max_columns', None)
df.head()

,location,make,model,short_description,price,mileage,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,warranty,first_registration,production_date,general_inspection,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,fuel_consumption,co2_emissions ( g/km),emission_class,emissions_sticker,comfort_convenience,entertainment_media,safety_security,extras,colour,paint,upholstery_colour,upholstery,warranty_category,full_service_encoded,non_smoker_encoded,fuel_cons_comb,fuel_cons_city,fuel_cons_country,air_conditioning,AppleCarPlay,abs_encoded
0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,08/2003,Gasoline,150,Dealer,Compact,Used,Front,5,3,6 months,08/2003,2003,05/2022,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1984,None,4,1280.000000,None,128,Euro 4,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, Radio]]","[[ABS, Alarm system, Central door lock, Centra...",[[Alloy wheels]],Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,None,NaN,NaN,1,[[CD player,0
1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,10/2013,Gasoline,125,Dealer,Compact,Used,Front,5,5,None,10/2013,2013,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1200.000000,4.9 l/100 km (comb.),128,None,NoNonee,"[[Air conditioning, Automatic climate control,...","[[CD player, Radio]]","[[Alarm system, Central door lock, Central doo...","[[Alloy wheels (16"")]]",White,1,"upholstery, Black",Cloth,NaN,1,0,4.9,NaN,NaN,1,[[CD player,5
2,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,06/2015,Gasoline,125,Dealer,Compact,Used,None,5,5,6 months,06/2015,2015,01/2024,Yes,Yes,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,None,4,1433.322061,"0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...",128,None,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[Bluetooth, CD player, On-board computer, USB]]","[[ABS, Central door lock with remote control, ...","[[Alloy wheels (15"")]]",Grey,0,NaN,NaN,1 year< :,1,1,0,0,0,1,[[Bluetooth,0
3,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,10/2015,Gasoline,125,Dealer,Compact,Used,Front,4,3,6 months,10/2015,2015,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,7,4,1105.000000,"4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...",111,Euro 6,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, MP3, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Shift paddles, Sport sea...",Black,1,"upholstery, Black",Part leather,1 year< :,1,0,4.8,5.9,4.2,1,[[CD player,0
4,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,10/2017,Gasoline,150,Dealer,Compact,Used,Front,5,5,6 months,10/2017,2017,11/2023,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1495,7,4,1215.000000,"5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...",113,Euro 6,NoNonee,"[[Air conditioning, Armrest, Electrical side m...","[[CD player, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Sport seats, Sport suspe...",Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,5,6.2,4.3,1,[[CD player,0

# 27-non_smoker_vehicle

In [128]:
df['non_smoker_vehicle'].value_counts()

non_smoker_vehicle
\n,None,\n    56455
\n,Yes,\n      4933
Name: count, dtype: int64

In [129]:
df['non_smoker_vehicle'] = df['non_smoker_vehicle'].str.replace(',', '').str.strip()
df['non_smoker_vehicle'].value_counts()

non_smoker_vehicle
None    56455
Yes      4933
Name: count, dtype: int64

In [130]:
lbe.fit_transform(df["non_smoker_vehicle"]) #Changed #dtype to int and changed to 0 and 1.

array([0, 0, 1, ..., 0, 0, 0])

In [131]:
df['non_smoker_encoded']=lbe.fit_transform(df["non_smoker_vehicle"])
df['non_smoker_encoded']

0        0
1        0
2        1
3        0
4        0
        ..
62761    0
62762    0
62763    0
62764    0
62765    0
Name: non_smoker_encoded, Length: 61388, dtype: int32

In [ ]:
#df.drop("non_smoker_encoded", inplace=True, axis=1)

# 28 Column Name : previous_owner

In [132]:
df['previous_owner'].value_counts()

previous_owner
[['\n'], ['None']]    57066
[['\n'], ['1']]        2640
[['\n'], ['2']]        1145
[['\n'], ['3']]         347
[['\n'], ['4']]         121
[['\n'], ['5']]          38
[['\n'], ['6']]          14
[['\n'], ['7']]           7
[['\n'], ['8']]           6
[['\n'], ['9']]           2
[['\n'], ['12']]          1
[['\n'], ['10']]          1
Name: count, dtype: int64

In [133]:
df['previous_owner'] = df['previous_owner'].str.lstrip("[' \s\S\t n ',]")
df['previous_owner'] = df['previous_owner'].str.rstrip("['\s,]")
df['previous_owner'].value_counts()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3764432220.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['previous_owner'] = df['previous_owner'].str.lstrip("[' \s\S\t n ',]")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3764432220.py:2: SyntaxWarning: invalid escape sequence '\s'
  df['previous_owner'] = df['previous_owner'].str.rstrip("['\s,]")

previous_owner
None    57066
1        2640
2        1145
3         347
4         121
5          38
6          14
7           7
8           6
9           2
12          1
10          1
Name: count, dtype: int64

In [228]:
df.drop("previous_owner", inplace=True, axis=1)

# 29 Column Name : last_timing_belt_change  # 61925 Since the value None means it never changes, it was thought to be filled with the production date.

In [135]:
df['last_timing_belt_change'] = df['last_timing_belt_change'].str.lstrip(" [',] '\a \s\S\t\r n ' ")
df['last_timing_belt_change'] = df['last_timing_belt_change'].str.rstrip(" [',] '\a \s\S\t\r n ' ")

df['last_timing_belt_change'].unique()
df['last_timing_belt_change'].value_counts()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\1847066085.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['last_timing_belt_change'] = df['last_timing_belt_change'].str.lstrip(" [',] '\a \s\S\t\r n ' ")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\1847066085.py:2: SyntaxWarning: invalid escape sequence '\s'
  df['last_timing_belt_change'] = df['last_timing_belt_change'].str.rstrip(" [',] '\a \s\S\t\r n ' ")

last_timing_belt_change
None       60549
06/2021       41
05/2021       31
10/2021       31
09/2021       28
           ...
02/2015        1
04/2016        1
06/2014        1
04/2015        1
11/2015        1
Name: count, Length: 82, dtype: int64

In [136]:
df.loc[(df['last_timing_belt_change'] == 'None'), ['last_timing_belt_change', 'first_registration', 'mileage']][:10]

  last_timing_belt_change first_registration   mileage
0                    None            08/2003  191066.0
1                    None            10/2013   94758.0
2                    None            06/2015  145102.0
3                    None            10/2015  119666.0
4                    None            10/2017   55815.0
5                    None            03/2019   47536.0
6                    None            03/2014   94530.0
7                    None            07/2011  139703.0
8                    None            08/2012  103626.0
9                    None            01/2011  100558.0

In [137]:
df['last_timing_belt_change'].isnull().sum()

0

# 30 Column Name : Power We delete this column because it is duplicate

In [138]:
df["Power"].describe()

count          61388
unique           360
top       \n,None,\n
freq            5263
Name: Power, dtype: object

In [139]:
df_origin["power"].describe()

count          62766
unique           361
top       [None, '']
freq            5333
Name: power, dtype: object

In [229]:
df.drop("Power", inplace=True, axis=1)

# 31-Gearbox

In [141]:
df['Gearbox'].value_counts()

Gearbox
Automatic         35899
Manual            24803
Semi-automatic      603
None                 83
Name: count, dtype: int64

# 32-engine_size

In [142]:
# Edit to include numbers only
df['engine_size'] = df['engine_size'].replace({'[^0-9]':''}, regex=True)

# Change empty data to NaN
df['engine_size'] = df['engine_size'].replace('', np.nan)

# Change data type to int
df['engine_size'] = df['engine_size'].astype('Int64')

df['engine_size'].value_counts()

engine_size
1598    4216
1998    2581
999     2213
1199    2202
1395    2041
        ...
3596       1
2          1
3604       1
1716       1
200        1
Name: count, Length: 443, dtype: Int64

In [143]:

df["engine_size"].isna().sum() #

5059

In [144]:
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,location,make,model,short_description,price,mileage,gearbox,registration,fuel_type,power,seller,body_type,type,drivetrain,seats,doors,country_version,offer_number,warranty,Mileage,first_registration,production_date,general_inspection,last_service,full_service_history,non_smoker_vehicle,previous_owner,last_timing_belt_change,Power,Gearbox,engine_size,gears,cylinders,empty_weight,Fuel_type,fuel_consumption,co2_emissions,emission_class,emissions_sticker,\nComfort & Convenience\n,\nEntertainment & Media\n,\nSafety & Security\n,extras,\ncolour,\nmanufacturer_color,\npaint,upholstery_colour,upholstery,warranty_category,full_service_encoded,non_smoker_encoded
0,0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,"\n,Automatic,\n",08/2003,Gasoline,150,Dealer,Compact,Used,Front,5,3,None,SJ-112-R,6 months,"[['\n'], ['']]",08/2003,2003,05/2022,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1984,"\n,None,\n","\n,4,\n","\n,1,280 kg,\n",Super 95,"\n,None,\n","['\n', [' ', ' ', ' '], '\n']","\n,Euro 4,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'Radio']]","[['ABS', 'Alarm system', 'Central door lock', ...",[['Alloy wheels']],"\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth",1 year< :,1,0
1,1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,"\n,Automatic,\n",10/2013,Gasoline,125,Dealer,Compact,Used,Front,5,5,None,809725,None,"[['\n'], ['']]",10/2013,2013,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,"\n,None,\n","\n,4,\n","\n,1,200 kg,\n",Gasoline,"['\n', ['4.9 l/100 km (comb.)', ' ', ' '], '\n']","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Automatic climate contr...","[['CD player', 'Radio']]","[['Alarm system', 'Central door lock', 'Centra...","[['Alloy wheels (16"")']]","\n4, White",NaN,NaN,"\nupholstery, Black","\n8, Cloth",NaN,1,0
2,3,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,"\n,Automatic,\n",06/2015,Gasoline,125,Dealer,Compact,Used,None,5,5,Netherlands,2601307,6 months,"[['\n'], ['']]",06/2015,2015,01/2024,NaN,Yes,Yes,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,"\n,None,\n","\n,4,\n","\n,None,\n",Gasoline,"['\n', ['0 l/100 km (comb.)', '0 l/100 km (cit...","\n,None,\n","\n,None,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['Bluetooth', 'CD player', 'On-board computer...","[['ABS', 'Central door lock with remote contro...","[['Alloy wheels (15"")']]","\n4, Grey",NaN,"\npaint, Metallic",NaN,NaN,1 year< :,1,1
3,4,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,"\n,Automatic,\n",10/2015,Gasoline,125,Dealer,Compact,Used,Front,4,3,None,L-847-SK,6 months,"[['\n'], ['']]",10/2015,2015,NaN,NaN,Yes,None,None,None,"\n,92 kW (125 hp),\n",Automatic,1395,"\n,7,\n","\n,4,\n","\n,1,105 kg,\n",Gasoline,"['\n', ['4.8 l/100 km (comb.)', '5.9 l/100 km ...","\n,111 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Automatic cl...","[['CD player', 'MP3', 'On-board computer', 'Ra...","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Shift paddles', 'Spor...","\n4, Black",NaN,NaN,"\nupholstery, Black","\n8, Part leather",1 year< :,1,0
4,7,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,"\n,Automatic,\n",10/2017,Gasoline,150,Dealer,Compact,Used,Front,5,5,None,PZ-744-H,6 months,"[['\n'], ['']]",10/2017,2017,11/2023,NaN,Yes,None,None,None,"\n,110 kW (150 hp),\n",Automatic,1495,"\n,7,\n","\n,4,\n","\n,1,215 kg,\n",Super 95,"['\n', ['5 l/100 km (comb.)', '6.2 l/100 km (c...","\n,113 g/km (comb.),\n","\n,Euro 6,\n","\n,None,\n","[['Air conditioning', 'Armrest', 'Electrical s...","[['CD player', 'On-board computer', 'Radio']]","[['ABS', 'Alarm system', 'Bi-Xenon headlights'...","[['Alloy wheels (17"")', 'Sport seats', 'Sport ...","\n4, Grey",NaN,"\npaint, Metallic","\nupholstery, Black","\n8, Cloth",1 year< :,1,0

# 33 -gears

In [145]:
df["gears"]=df["gears"].str.strip(',\n,')
df["gears"].unique()
df["gears"].value_counts()

gears
6       18362
None    17850
5       10582
7        6743
8        4797
1        1533
9         872
4         604
2          37
3           8
Name: count, dtype: int64

In [146]:
df.loc[(df['gears'] == 'None'), ['gears', 'model','gearbox']][:15]

   gears model          gearbox
0   None    A3  \n,Automatic,\n
1   None    A3  \n,Automatic,\n
2   None    A1  \n,Automatic,\n
5   None    A3  \n,Automatic,\n
7   None    A3  \n,Automatic,\n
8   None    A1  \n,Automatic,\n
12  None    A5  \n,Automatic,\n
13  None    A1  \n,Automatic,\n
14  None    A5  \n,Automatic,\n
20  None    A3  \n,Automatic,\n
23  None    A3  \n,Automatic,\n
30  None    A3  \n,Automatic,\n
39  None    A1  \n,Automatic,\n
40  None    A5  \n,Automatic,\n
41  None    A1  \n,Automatic,\n

In [147]:
def fill_gears(row):
    if pd.isnull(row['gears']):
        model = row['model']
        return f"{model} "
    else:
        return row['gears']

# 'gears' sütunundaki eksik değerleri 'model' bilgisine göre dolduruyoruz
df['gears'] = df.apply(fill_gears, axis=1)

In [148]:
df["gears"].value_counts()

gears
6       18362
None    17850
5       10582
7        6743
8        4797
1        1533
9         872
4         604
2          37
3           8
Name: count, dtype: int64

# 34-cylinders

In [149]:
df["cylinders"].value_counts() #5432 None values

cylinders
\n,4,\n       41075
\n,3,\n        7522
\n,None,\n     5432
\n,6,\n        4133
\n,5,\n        1341
\n,8,\n         905
\n,1,\n         497
\n,2,\n         392
\n,10,\n         65
\n,12,\n         25
\n,7,\n           1
Name: count, dtype: int64

In [150]:
df["cylinders"]=df["cylinders"].str.strip(',\n,')
df["cylinders"] = pd.to_numeric(df["cylinders"], errors='coerce')
df["cylinders"].fillna(df["cylinders"].mean(), inplace=True)
df["cylinders"] = df["cylinders"].astype(int)

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3681633673.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["cylinders"].fillna(df["cylinders"].mean(), inplace=True)

In [151]:
df["cylinders"].value_counts()

cylinders
4     46507
3      7522
6      4133
5      1341
8       905
1       497
2       392
10       65
12       25
7         1
Name: count, dtype: int64

#  35-empty_weight

In [152]:
df_origin["empty_weight"].value_counts()

empty_weight
\n,1,295 kg,\n    1529
\n,None,\n        1407
\n,1,405 kg,\n    1127
\n,1,635 kg,\n     795
\n,1,065 kg,\n     658
                  ...
\n,2,387 kg,\n       1
\n,2,481 kg,\n       1
\n,2,163 kg,\n       1
\n,2,283 kg,\n       1
\n,2,036 kg,\n       1
Name: count, Length: 1539, dtype: int64

In [153]:
df_origin["empty_weight"].head(30)

0     \n,1,280 kg,\n
1     \n,1,200 kg,\n
2         \n,None,\n
3     \n,1,105 kg,\n
4     \n,1,215 kg,\n
5     \n,1,180 kg,\n
6     \n,1,125 kg,\n
7     \n,1,310 kg,\n
8     \n,1,125 kg,\n
9     \n,1,345 kg,\n
10    \n,1,285 kg,\n
11    \n,1,150 kg,\n
12    \n,1,500 kg,\n
13    \n,1,065 kg,\n
14    \n,1,525 kg,\n
15    \n,1,490 kg,\n
16    \n,1,200 kg,\n
17    \n,1,500 kg,\n
18    \n,1,210 kg,\n
19    \n,1,255 kg,\n
20    \n,1,175 kg,\n
21    \n,1,115 kg,\n
22    \n,1,175 kg,\n
23    \n,1,210 kg,\n
24    \n,1,590 kg,\n
25    \n,1,285 kg,\n
26    \n,1,165 kg,\n
27    \n,1,125 kg,\n
28    \n,1,190 kg,\n
29    \n,1,255 kg,\n
Name: empty_weight, dtype: object

In [154]:
df["empty_weight"]=df["empty_weight"].str.strip('[\n,')
df["empty_weight"]=df["empty_weight"].str.replace(' kg', '').str.replace(',', '')
df["empty_weight"].head()

0    1280
1    1200
2    None
3    1105
4    1215
Name: empty_weight, dtype: object

In [155]:
# 'None' değerlerini np.nan ile değiştir
df["empty_weight"] = df["empty_weight"].replace('None' , np.nan)

# 'float' türüne dönüştür
df["empty_weight"] = df["empty_weight"].astype(float)

# 'pd.Int64Dtype()' türüne dönüştür
df["empty_weight"] = df["empty_weight"].astype(pd.Int64Dtype())

# 'empty_weight' sütunundaki eksik değerlerin sayısını kontrol et
df["empty_weight"].isna().sum()

1387

In [156]:
#Eksik değerleri, diğer benzer örneklerin (komşuların) değerlerine göre tahmin etmek için KNN algoritmasını kullandık.
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
df['empty_weight'] = imputer.fit_transform(df[['empty_weight']])

In [157]:
df["empty_weight"].isna().sum()

0

In [158]:
df["empty_weight"].head()

0    1280.000000
1    1200.000000
2    1433.322061
3    1105.000000
4    1215.000000
Name: empty_weight, dtype: float64

# 36-Fuel_type

In [159]:
df["Fuel_type"].value_counts()

Fuel_type
Gasoline                                        22377
Super 95                                        17309
Diesel                                          10527
None                                             8646
Diesel (Particle filter)                         1197
Super E10 95                                      404
LPG                                               305
Liquid petroleum gas (LPG)                        235
Gasoline (Particle filter)                        140
Electric                                           73
Domestic gas L                                     54
CNG                                                40
Super Plus 98                                      27
Super 95 (Particle filter)                         23
Hydogen                                            12
Ethanol                                             9
Regular/Benzine 91                                  4
Others                                              3
Electric (Particle filter)                          1
Domestic gas L (Particle filter)                    1
Liquid petroleum gas (LPG) (Particle filter)        1
Name: count, dtype: int64

In [160]:
df["Fuel_type"]=df["Fuel_type"].str.strip('[\n,')
df["Fuel_type"].head(15)

0     Super 95
1     Gasoline
2     Gasoline
3     Gasoline
4     Super 95
5     Super 95
6     Gasoline
7     Gasoline
8     Gasoline
9     Super 95
10    Gasoline
11    Super 95
12    Gasoline
13    Super 95
14    Gasoline
Name: Fuel_type, dtype: object

In [161]:
most_common_fuel_type = df["Fuel_type"].mode()[0]  # 'Fuel_type' sütununun en yaygın değeri
df["Fuel_type"].fillna(most_common_fuel_type, inplace=True)

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3401968887.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Fuel_type"].fillna(most_common_fuel_type, inplace=True)

In [162]:
df["Fuel_type"].value_counts()

Fuel_type
Gasoline                                        22377
Super 95                                        17309
Diesel                                          10527
None                                             8646
Diesel (Particle filter)                         1197
Super E10 95                                      404
LPG                                               305
Liquid petroleum gas (LPG)                        235
Gasoline (Particle filter)                        140
Electric                                           73
Domestic gas L                                     54
CNG                                                40
Super Plus 98                                      27
Super 95 (Particle filter)                         23
Hydogen                                            12
Ethanol                                             9
Regular/Benzine 91                                  4
Others                                              3
Electric (Particle filter)                          1
Domestic gas L (Particle filter)                    1
Liquid petroleum gas (LPG) (Particle filter)        1
Name: count, dtype: int64

# 37 Column name : fuel_consumption # city -country and comb. columns will be created.

In [163]:
df['fuel_consumption'] = df['fuel_consumption'].str.lstrip(" [', \s\S\t\r\n,n ' ")
df['fuel_consumption'] = df['fuel_consumption'].str.rstrip("[', '] \s\S\t\r\n,\\n  ")
df['fuel_consumption'] = df['fuel_consumption'].str.replace("'","")
df['fuel_consumption']

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\1473338196.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['fuel_consumption'] = df['fuel_consumption'].str.lstrip(" [', \s\S\t\r\n,n ' ")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\1473338196.py:2: SyntaxWarning: invalid escape sequence '\s'
  df['fuel_consumption'] = df['fuel_consumption'].str.rstrip("[', '] \s\S\t\r\n,\\n  ")

0                                                     None
1                                     4.9 l/100 km (comb.)
2        0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...
3        4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...
4        5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...
                               ...
62761                                                 None
62762                                                 None
62763    9.1 l/100 km (comb.), 12.6 l/100 km (city), 7 ...
62764                                                 None
62765    8.4 l/100 km (comb.), 11.6 l/100 km (city), 6....
Name: fuel_consumption, Length: 61388, dtype: object

In [164]:
df['fuel_cons_comb'] = df['fuel_consumption'].str.split(',').str.get(0)
df['fuel_cons_comb'].head()

0                    None
1    4.9 l/100 km (comb.)
2      0 l/100 km (comb.)
3    4.8 l/100 km (comb.)
4      5 l/100 km (comb.)
Name: fuel_cons_comb, dtype: object

In [165]:
df['fuel_cons_comb'] = df['fuel_cons_comb'].str.replace("l/100 km (comb.)","")
df["fuel_cons_comb"]

0        None
1        4.9
2          0
3        4.8
4          5
         ...
62761    None
62762    None
62763    9.1
62764    None
62765    8.4
Name: fuel_cons_comb, Length: 61388, dtype: object

In [166]:
df['fuel_cons_city'] = df['fuel_consumption'].str.split(',').str.get(1)
df['fuel_cons_city'].head()

0                     NaN
1                     NaN
2       0 l/100 km (city)
3     5.9 l/100 km (city)
4     6.2 l/100 km (city)
Name: fuel_cons_city, dtype: object

In [167]:
df['fuel_cons_city'] = df['fuel_cons_city'].str.replace("l/100 km (city)","")
df["fuel_cons_city"].head()

0      NaN
1      NaN
2       0
3     5.9
4     6.2
Name: fuel_cons_city, dtype: object

In [168]:
df['fuel_cons_country'] = df['fuel_consumption'].str.split(',').str.get(2)
df['fuel_cons_country'].head()

0                        NaN
1                        NaN
2       0 l/100 km (country)
3     4.2 l/100 km (country)
4     4.3 l/100 km (country)
Name: fuel_cons_country, dtype: object

In [169]:
df['fuel_cons_country'] = df['fuel_cons_country'].str.replace("l/100 km (country)","")
df["fuel_cons_country"].head()

0      NaN
1      NaN
2       0
3     4.2
4     4.3
Name: fuel_cons_country, dtype: object

# 38--co2_emissions

In [170]:
df["co2_emissions"].value_counts()

co2_emissions
\n,None,\n                       9681
['\n', [' ', ' ', ' '], '\n']    6767
\n,0 g/km (comb.),\n             4904
\n,139 g/km (comb.),\n           1046
\n,149 g/km (comb.),\n            888
                                 ...
\n,400 g/km (comb.),\n              1
\n,67 g/km (comb.),\n               1
\n,329 g/km (comb.),\n              1
\n,55 g/km (comb.),\n               1
\n,70 g/km (comb.),\n               1
Name: count, Length: 346, dtype: int64

In [171]:
df["co2_emissions"]=df["co2_emissions"].str.strip('\n,')
df["co2_emissions"]=df["co2_emissions"].str.split().str[0]

In [172]:
df["co2_emissions"] = pd.to_numeric(df["co2_emissions"], errors='coerce')
df["co2_emissions"].fillna(df["co2_emissions"].mean(), inplace=True)
df["co2_emissions"] = df["co2_emissions"].astype(int)
df['co2_emissions'].isna().sum()

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\2403431788.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["co2_emissions"].fillna(df["co2_emissions"].mean(), inplace=True)

0

In [173]:
df["co2_emissions"].head()

0    128
1    128
2    128
3    111
4    113
Name: co2_emissions, dtype: int32

In [174]:
df.rename(columns={'co2_emissions': 'co2_emissions ( g/km)'}, inplace=True) #sütun ismine birim değeri geldi ve değişti.

In [175]:
df['co2_emissions ( g/km)']

0        128
1        128
2        128
3        111
4        113
        ...
62761    128
62762    128
62763    215
62764    128
62765    207
Name: co2_emissions ( g/km), Length: 61388, dtype: int32

# 39-emission_class

In [176]:
df['emission_class'].value_counts()

emission_class
\n,Euro 6,\n                     19296
\n,None,\n                       18731
\n,Euro 5,\n                     10349
\n,Euro 4,\n                      7490
\n,Euro 6d-TEMP,\n                2640
\n,Euro 3,\n                      1676
['\n', [' ', ' ', ' '], '\n']      587
\n,Euro 1,\n                       455
\n,Euro 2,\n                       127
\n,Euro 6c,\n                       20
\n,Euro 6d,\n                       17
Name: count, dtype: int64

In [177]:
df['emission_class'] = df['emission_class'].apply(lambda x: str(x).strip('\n').strip())
df['emission_class'] = df['emission_class'].str.strip(',.\'[]" ')
df['emission_class'].replace("\\n', [' ', ' ', ' '], '\\n", "None", inplace=True)
#df["emission_class"].replace("None", None, inplace = True)

df['emission_class'].value_counts()
# df.emission_class.value_counts(dropna = True).plot.bar()

C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3562272591.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['emission_class'].replace("\\n', [' ', ' ', ' '], '\\n", "None", inplace=True)

emission_class
None            19318
Euro 6          19296
Euro 5          10349
Euro 4           7490
Euro 6d-TEMP     2640
Euro 3           1676
Euro 1            455
Euro 2            127
Euro 6c            20
Euro 6d            17
Name: count, dtype: int64

In [178]:
#none değerler bir sütundaki korelasyona göre doldurulabilir.

# 40-emissions_sticker

In [179]:
df["emissions_sticker"].unique()

array(['\n,None,\n', '\n,4 (Green),\n', '\n,3 (Yellow),\n',
       '\n,1 (No sticker),\n', "['\\n', [' ', ' ', ' '], '\\n']",
       '\n,2 (Red),\n'], dtype=object)

In [180]:
df["emissions_sticker"] = df["emissions_sticker"].str.rstrip(" [',] \s\S\t\r\n ' ")
df["emissions_sticker"] = df["emissions_sticker"].str.lstrip(" [',] \s\S\t\r\n ' ")
df["emissions_sticker"] = df["emissions_sticker"].str.strip(",")
df["emissions_sticker"] = df["emissions_sticker"].str.replace("n","None")
df["emissions_sticker"].value_counts()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3624429367.py:1: SyntaxWarning: invalid escape sequence '\s'
  df["emissions_sticker"] = df["emissions_sticker"].str.rstrip(" [',] \s\S\t\r\n ' ")
C:\Users\CC\AppData\Local\Temp\ipykernel_7360\3624429367.py:2: SyntaxWarning: invalid escape sequence '\s'
  df["emissions_sticker"] = df["emissions_sticker"].str.lstrip(" [',] \s\S\t\r\n ' ")

emissions_sticker
NoNonee                           61254
4 (GreeNone)                        106
1 (No sticker)                       12
None', [' ', ' ', ' '], '\None       11
3 (Yellow)                            4
2 (Red)                               1
Name: count, dtype: int64

In [181]:
#bu sütun da bir önceki sütunla arasındaki korelasyon ile doldurulabilir. Ancak karmaşık ifadeler var belirli bir anlam ifade etmeyedebilir bakmak lazım.

In [182]:
#df.drop("emissions_sticker", inplace=False, axis=1)

# 41 Column Name : Comfort & Convenience   #Air Conditioning -Cruise control columns will be created and arranged as 0-1.

In [183]:
# Sütun adını değiştir
df.rename(columns={'\nComfort & Convenience\n': 'comfort_convenience'}, inplace=True)

# '\n' karakterlerini kaldır ve tek tırnakları temizle
df['comfort_convenience'] = df['comfort_convenience'].str.replace('\n', '').str.replace("'", '')

# Sonuçları yazdır
df['comfort_convenience'].unique()

array(['[[Air conditioning, Armrest, Automatic climate control, Electrical side mirrors, Navigation system, Power windows, Sunroof]]',
       '[[Air conditioning, Automatic climate control, Electrical side mirrors, Light sensor, Power windows, Rain sensor]]',
       '[[Air conditioning, Armrest, Automatic climate control, Cruise control, Navigation system, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats]]',
       ...,
       '[[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Electrically adjustable seats, Leather steering wheel, Parking assist system sensors rear, Rain sensor, Seat heating]]',
       '[[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Parking assist system sensors rear, Power windows, Rain sensor, Sunroof]]',
       '[[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Navigation system, Power windows, Sunroof]]'],
      dtype=object)

In [184]:
df['comfort_convenience'].value_counts()

comfort_convenience
[[Air conditioning, Power windows]]                                                                                                                                                                                                                                                                                                                                                 244
[[Air conditioning, Electrical side mirrors, Power windows]]                                                                                                                                                                                                                                                                                                                        227
[[Air conditioning, Electrical side mirrors, Power windows, Tinted windows]]                                                                                                                                                                                                                                                                                                        146
[[Air conditioning, Cruise control, Electrical side mirrors, Power windows]]                                                                                                                                                                                                                                                                                                        119
[[Power windows]]                                                                                                                                                                                                                                                                                                                                                                   117
                                                                                                                                                                                                                                                                                                                                                                                   ...
[[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrically adjustable seats, Multi-function steering wheel, Navigation system, Power windows]]                                                                                                                                                                                                              1
[[Air conditioning, Cruise control, Electric backseat adjustment, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Hill Holder, Leather steering wheel, Lumbar support, Navigation system, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Split rear seats]]      1
[[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Electrically adjustable seats, Light sensor, Multi-function steering wheel, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Tinted windows]]                                                                      1
[[Air conditioning, Air suspension, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Electrically adjustable seats, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Seat heating]]                                        1
[[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Navigation system, Power windows, Sunroof]]                                                                                                                                                                                                                           1
Name: count, Length: 28013, dtype: int64

# air_conditioning Column created and filled as 1-0.

In [185]:


df['air_conditioning'] = df['comfort_convenience'].str.split(',').str.get(0)

df['air_conditioning'].head()

#df['air_conditioning1'] = df['air_conditioning1'].fillna("None")
#df.loc[(df['air_conditioning1'] != 'None'), ['air_conditioning1', 'air_conditioning']]

0    [[Air conditioning
1    [[Air conditioning
2    [[Air conditioning
3    [[Air conditioning
4    [[Air conditioning
Name: air_conditioning, dtype: object

In [186]:
lbe.fit_transform(df["air_conditioning"])

array([1, 1, 1, ..., 1, 1, 1])

In [187]:
df['air_conditioning']=lbe.fit_transform(df["air_conditioning"])
df['air_conditioning'].head()

0    1
1    1
2    1
3    1
4    1
Name: air_conditioning, dtype: int32

# 42--Entertaiment & Media

In [188]:
df['\nEntertainment & Media\n'].unique()

array(["[['CD player', 'Radio']]",
       "[['Bluetooth', 'CD player', 'On-board computer', 'USB']]",
       "[['CD player', 'MP3', 'On-board computer', 'Radio']]", ...,
       "[['Android Auto', 'Apple CarPlay', 'Digital cockpit', 'Induction charging for smartphones', 'MP3', 'On-board computer', 'Radio', 'USB']]",
       "[['Apple CarPlay', 'CD player', 'On-board computer', 'Radio', 'Sound system']]",
       "[['Android Auto', 'Apple CarPlay', 'Bluetooth', 'CD player', 'Digital cockpit', 'Digital radio', 'Hands-free equipment', 'Induction charging for smartphones', 'Integrated music streaming', 'On-board computer', 'Radio', 'Sound system', 'USB']]"],
      dtype=object)

In [189]:
# Sütun adını değiştir
df.rename(columns={'\nEntertainment & Media\n': 'entertainment_media'}, inplace=True)

# '\n' karakterlerini ve tek tırnakları kaldır
df['entertainment_media'] = df['entertainment_media'].str.replace('\n', '').str.replace("'", '')

# Sonuçları yazdır
df['entertainment_media'].unique()

array(['[[CD player, Radio]]',
       '[[Bluetooth, CD player, On-board computer, USB]]',
       '[[CD player, MP3, On-board computer, Radio]]', ...,
       '[[Android Auto, Apple CarPlay, Digital cockpit, Induction charging for smartphones, MP3, On-board computer, Radio, USB]]',
       '[[Apple CarPlay, CD player, On-board computer, Radio, Sound system]]',
       '[[Android Auto, Apple CarPlay, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, On-board computer, Radio, Sound system, USB]]'],
      dtype=object)

In [190]:
search_value = 'Apple CarPlay'

# selecting the relevant rows by searching inside the column
search_result = df[df['entertainment_media'].str.contains(search_value)]

# print the search result
if not search_result.empty:
    print(f"The number you are looking for ({search_value}) available in the rows in the dataset:")
    print(search_result)
else:
    print(f"The number you are looking for({search_value}) vnot available in the rows in the dataset.")

The number you are looking for (Apple CarPlay) available in the rows in the dataset:
       Unnamed: 0           location    make model  \
75             96       KROMMENIE,NL   Audi     A3
80            101       APELDOORN,NL   Audi     A3
127           152  SHERTOGENBOSCH,NL   Audi     A5
128           153  SHERTOGENBOSCH,NL   Audi     A5
164           194          ARNHEM,NL   Audi     A3
...           ...                ...     ...   ...
62592       70913         UTRECHT,NL  Volvo   XC90
62593       70914          VEGHEL,NL  Volvo   XC60
62669       70998      LEKKERKERK,NL  Volvo    V60
62680       71012      OOSTERHOUT,NL  Volvo    V60
62688       71020      HARDENBERG,NL  Volvo    V60

                                       short_description         price  \
75                                    1.4 TFSI Ambit. PL  13750.000000
80               1.4 TFSI Attraction Proline Plus G-tron  13495.000000
127                                     2.0 TFSI quattro  11511.000000
128                                     2.0 TFSI quattro  11511.000000
164    Sportback 35 TFSI S edition | 19-Inch | Matrix...  39950.000000
...                                                  ...           ...
62592                             B5 AWD R-Design Diesel  24621.765117
62593  2.0 B4 AWD Momentum Pro Leder Panoramadak Trek...  44995.000000
62669  2.4 D5 Twin Engine Lease Edition AUT EX BTW (€...  16940.000000
62680                         2.4 D6 AWD Plug in hybride  12999.000000
62688                               2.4 D6 AWD Pl.i Sum.  10500.000000

        mileage          gearbox registration        fuel_type  power  \
75     132000.0  \n,Automatic,\n      12/2013         Gasoline    122
80     101000.0  \n,Automatic,\n      10/2014         Gasoline    110
127    153186.0  \n,Automatic,\n      11/2009         Gasoline    211
128    153186.0  \n,Automatic,\n      11/2009         Gasoline    211
164     14334.0  \n,Automatic,\n      03/2021         Gasoline    150
...         ...              ...          ...              ...    ...
62592    6411.0  \n,Automatic,\n      07/2021  Electric/Diesel    157
62593   95166.0  \n,Automatic,\n      09/2019  Electric/Diesel    197
62669  132740.0  \n,Automatic,\n      12/2016  Electric/Diesel    163
62680  197000.0  \n,Automatic,\n      01/2015  Electric/Diesel    286
62688  320000.0  \n,Automatic,\n      05/2013  Electric/Diesel    215

               seller         body_type  type drivetrain seats doors  \
75     Private seller           Compact  Used      Front     5     4
80     Private seller           Compact  Used       None     5     4
127    Private seller           Compact  Used       None     4     4
128    Private seller           Compact  Used       None     4     4
164            Dealer           Compact  Used      Front     5     5
...               ...               ...   ...        ...   ...   ...
62592          Dealer  Off-Road/Pick-up  Used        4WD     7     5
62593          Dealer  Off-Road/Pick-up  Used        4WD     5     5
62669          Dealer     Station wagon  Used        4WD     5     5
62680  Private seller     Station wagon  Used        4WD     5     5
62688  Private seller     Station wagon  Used        4WD     5     5

      country_version offer_number  warranty         Mileage  \
75               None         None      None  [['\n'], ['']]
80               None         None      None  [['\n'], ['']]
127              None         None      None  [['\n'], ['']]
128              None         None      None  [['\n'], ['']]
164              None     N-372-DL  6 months  [['\n'], ['']]
...               ...          ...       ...             ...
62592         Austria     N-591-PG      None  [['\n'], ['']]
62593            None     H-535-TT      None  [['\n'], ['']]
62669            None     KZ-479-N      None  [['\n'], ['']]
62680            None         None      None  [['\n'], ['']]
62688            None         None      None  [['\n'], ['']]

      first_registration production_date general_inspection  last_service  \
75               12/2013            2013            05/2023           NaN
80               10/2014            2014            10/2022           NaN
127              11/2009            2009            10/2023           NaN
128              11/2009            2009            09/2022           NaN
164              03/2021            2021                NaN           NaN
...                  ...             ...                ...           ...
62592            07/2021            2021            07/2024           NaN
62593            09/2019            2019            09/2022           NaN
62669            12/2016            2016                NaN           NaN
62680            01/2015            2015            02/2022           NaN
62688            05/2013            2013            12/2022           NaN

      full_service_history non_smoker_vehicle previous_owner  \
75                     Yes                Yes              1
80                     Yes                Yes           None
127                   None               None           None
128                   None               None           None
164                    Yes               None           None
...                    ...                ...            ...
62592                  Yes               None           None
62593                 None               None           None
62669                  Yes               None              1
62680                  Yes               None              2
62688                  Yes                Yes              1

      last_timing_belt_change                  Power    Gearbox  engine_size  \
75                    03/2021   \n,90 kW (122 hp),\n  Automatic         1395
80                       None   \n,81 kW (110 hp),\n  Automatic         1395
127                      None  \n,155 kW (211 hp),\n  Automatic         1984
128                      None  \n,155 kW (211 hp),\n  Automatic         1984
164                      None  \n,110 kW (150 hp),\n  Automatic         1498
...                       ...                    ...        ...          ...
62592                    None             \n,None,\n  Automatic         1969
62593                    None  \n,145 kW (197 hp),\n  Automatic         1969
62669                    None  \n,120 kW (163 hp),\n  Automatic         2400
62680                 02/2020  \n,210 kW (286 hp),\n  Automatic         2400
62688                 10/2019  \n,158 kW (215 hp),\n  Automatic         2400

      gears  cylinders  empty_weight Fuel_type  \
75     None          4        1200.0  Gasoline
80     None          4        1255.0  Gasoline
127    None          4        1590.0  Gasoline
128    None          4        1590.0  Gasoline
164       7          4        1295.0  Super 95
...     ...        ...           ...       ...
62592     8          4        2070.0    Diesel
62593     8          4        1850.0    Diesel
62669     6          5        1880.0    Diesel
62680     6          5        1849.0      None
62688     7          5        1848.0      None

                                        fuel_consumption  \
75     5 l/100 km (comb.), 6.1 l/100 km (city), 4.3 l...
80               5 l/100 km (comb.), 6.2 l/100 km (city)
127    7.4 l/100 km (comb.), 9.3 l/100 km (city), 6.3...
128    7.4 l/100 km (comb.), 9.3 l/100 km (city), 6.3...
164                                 4.8 l/100 km (comb.)
...                                                  ...
62592
62593
62669                                               None
62680  5.5 l/100 km (comb.), 5 l/100 km (city), 5.5 l...
62688                                               None

       co2_emissions ( g/km) emission_class emissions_sticker  \
75                       116         Euro 5           NoNonee
80                       115         Euro 6           NoNonee
127                      172         Euro 5           NoNonee
128                      172         Euro 5           NoNonee
164                        0           None           NoNonee
...                      ...            ...               ...
62592                    150         Euro 6           NoNonee
62593                    142   Euro 6d-TEMP           NoNonee
62669                     48           None           NoNonee
62680                     48         Euro 5           NoNonee
62688                    128           None           NoNonee

                                     comfort_convenience  \
75     [[Air conditioning, Armrest, Auxiliary heating...
80     [[Air conditioning, Armrest, Automatic climate...
127    [[360° camera, Air suspension, Automatic clima...
128    [[Air conditioning, Air suspension, Armrest, A...
164    [[Air conditioning, Armrest, Automatic climate...
...                                                  ...
62592  [[Air conditioning, Armrest, Automatic climate...
62593  [[Air conditioning, Armrest, Automatic climate...
62669  [[Air conditioning, Automatic climate control,...
62680  [[Air conditioning, Armrest, Automatic climate...
62688  [[Air conditioning, Air suspension, Armrest, A...

                                     entertainment_media  \
75     [[Apple CarPlay, Bluetooth, CD player, Hands-f...
80     [[Apple CarPlay, Bluetooth, Hands-free equipme...
127    [[Apple CarPlay, Induction charging for smartp...
128    [[Apple CarPlay, Bluetooth, Television, WLAN /...
164    [[Android Auto, Apple CarPlay, Digital cockpit...
...                                                  ...
62592  [[Android Auto, Apple CarPlay, Induction charg...
62593  [[Android Auto, Apple CarPlay, Digital cockpit...
62669  [[Android Auto, Apple CarPlay, CD player, MP3,...
62680  [[Android Auto, Apple CarPlay, Bluetooth, CD p...
62688  [[Android Auto, Apple CarPlay, Bluetooth, CD p...

                                   \nSafety & Security\n  \
75     [['ABS', 'Alarm system', 'Bi-Xenon headlights'...
80     [['ABS', 'Bi-Xenon headlights', 'Central door ...
127    [['Bi-Xenon headlights', 'Distance warning sys...
128    [['ABS', 'Daytime running lights', 'Full-LED h...
164    [['ABS', 'Adaptive Cruise Control', 'Adaptive ...
...                                                  ...
62592  [['ABS', 'Adaptive Cruise Control', 'Adaptive ...
62593  [['ABS', 'Adaptive Cruise Control', 'Adaptive ...
62669  [['ABS', 'Central door lock', 'Central door lo...
62680  [['ABS', 'Adaptive headlights', 'Alarm system'...
62688  [['ABS', 'Adaptive Cruise Control', 'Adaptive ...

                                                  extras    \ncolour  \
75                                     [['Sport seats']]  \n4, Black
80     [['Alloy wheels', 'Automatically dimming inter...   \n4, Grey
127    [['Electronic parking brake', 'Handicapped ena...   \n4, Grey
128    [['Alloy wheels', 'Automatically dimming inter...   \n4, Grey
164    [['Alloy wheels (19")', 'Automatically dimming...  \n4, White
...                                                  ...         ...
62592  [['Alloy wheels', 'Roof rack', 'Shift paddles'...  \n4, Black
62593  [['Alloy wheels (18")', 'Automatically dimming...   \n4, Blue
62669                           [['Alloy wheels (17")']]   \n4, Grey
62680  [['Alloy wheels (17")', 'Automatically dimming...   \n4, Blue
62688  [['Alloy wheels', 'Automatically dimming inter...   \n4, Grey

       \nmanufacturer_color            \npaint   upholstery_colour   \
75                      NaN                NaN  \nupholstery, Black
80                      NaN                NaN                  NaN
127                     NaN                NaN                  NaN
128                     NaN                NaN                  NaN
164                     NaN                NaN   \nupholstery, Grey
...                     ...                ...                  ...
62592                   NaN  \npaint, Metallic  \nupholstery, Black
62593                   NaN  \npaint, Metallic                  NaN
62669                   NaN  \npaint, Metallic  \nupholstery, Black
62680                   NaN  \npaint, Metallic  \nupholstery, Black
62688                   NaN  \npaint, Metallic  \nupholstery, Black

             upholstery  warranty_category  full_service_encoded  \
75            \n8, Cloth               NaN                     1
80                   NaN               NaN                     1
127                  NaN               NaN                     0
128                  NaN               NaN                     0
164           \n8, Cloth      1 year<    :                     1
...                  ...               ...                   ...
62592  \n8, Part leather               NaN                     1
62593  \n8, Full leather               NaN                     0
62669  \n8, Full leather               NaN                     1
62680  \n8, Full leather               NaN                     1
62688  \n8, Full leather               NaN                     1

       non_smoker_encoded fuel_cons_comb fuel_cons_city fuel_cons_country  \
75                      1             5            6.1               4.3
80                      1             5            6.2                NaN
127                     0           7.4            9.3               6.3
128                     0           7.4            9.3               6.3
164                     0           4.8             NaN               NaN
...                   ...            ...            ...               ...
62592                   0                           NaN               NaN
62593                   0                           NaN               NaN
62669                   0           None            NaN               NaN
62680                   0           5.5              5               5.5
62688                   1           None            NaN               NaN

       air_conditioning
75                    1
80                    1
127                   0
128                   1
164                   1
...                 ...
62592                 1
62593                 1
62669                 1
62680                 1
62688                 1

[13712 rows x 56 columns]

In [191]:
df['AppleCarPlay'] = df['entertainment_media'].str.split(',').str.get(0)

df['AppleCarPlay'].head()

0    [[CD player
1    [[CD player
2    [[Bluetooth
3    [[CD player
4    [[CD player
Name: AppleCarPlay, dtype: object

# 43--Safety & Security

In [192]:
df["\nSafety & Security\n"]

0        [['ABS', 'Alarm system', 'Central door lock', ...
1        [['Alarm system', 'Central door lock', 'Centra...
2        [['ABS', 'Central door lock with remote contro...
3        [['ABS', 'Alarm system', 'Bi-Xenon headlights'...
4        [['ABS', 'Alarm system', 'Bi-Xenon headlights'...
                               ...
62761    [['ABS', 'Central door lock', 'Central door lo...
62762    [['ABS', 'Central door lock', 'Central door lo...
62763    [['ABS', 'Central door lock', 'Central door lo...
62764    [['ABS', 'Central door lock with remote contro...
62765    [['ABS', 'Alarm system', 'Central door lock', ...
Name: \nSafety & Security\n, Length: 61388, dtype: object

In [193]:
df.rename(columns={'\nSafety & Security\n': 'safety_security'}, inplace=True)

# '\n' karakterlerini ve tek tırnakları kaldır
df['safety_security'] = df['safety_security'].str.replace('\n', '').str.replace("'", '')

# Sonuçları yazdır
df['safety_security'].unique()

array(['[[ABS, Alarm system, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Passenger-side airbag, Power steering, Side airbag, Traction contro]]',
       '[[Alarm system, Central door lock, Central door lock with remote control, Fog lights, Immobilizer]]',
       '[[ABS, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction contro]]',
       ...,
       '[[ABS, Adaptive headlights, Bi-Xenon headlights, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Traction control, Xenon headlights]]',
       '[[ABS, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Isofix, Power steering, Side airbag, Traction contro]]',
       '[[ABS, Alarm system, Central door lock, Central door lock with remote control, Daytime running lights, Driver-side airbag, Electronic stability control, Head airbag, Immobilizer, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Traction control, Xenon headlights]]'],
      dtype=object)

In [194]:
search_value = 'ABS'

# selecting the relevant rows by searching inside the column
search_result = df[df['safety_security'].str.contains(search_value)]

# print the search result
if not search_result.empty:
    print(f"The number you are looking for ({search_value}) available in the rows in the dataset:")
    print(search_result)
else:
    print(f"The number you are looking for({search_value}) vnot available in the rows in the dataset.")

The number you are looking for (ABS) available in the rows in the dataset:
       Unnamed: 0              location    make model  \
0               0       LOON OP ZAND,NL   Audi     A3
2               3       BAARLENASSAU,NL   Audi     A1
3               4            ZUTPHEN,NL   Audi     A1
4               7        HAAKSBERGEN,NL   Audi     A3
5               8              WEZEP,NL   Audi     A3
...           ...                   ...     ...   ...
62761       71098          ETTENLEUR,NL  Volvo    S60
62762       71099  HENDRIKIDOAMBACHT,NL  Volvo    S60
62763       71101           LELYSTAD,NL  Volvo    S60
62764       71102          AMSTERDAM,NL  Volvo    S40
62765       71103        SOESTERBERG,NL  Volvo    S60

                                       short_description    price  \
0                              2.0 FSI Ambition Pro Line   4450.0
2        1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.  12450.0
3      S-Line | Automaat | Navigatie | Cruise-/Climat...  14945.0
4      Sportback 1.5 TFSI Sport | Dealer Onderhouden ...  24900.0
5                             Sportback 30 TFSI/Automaat  24750.0
...                                                  ...      ...
62761                          2.4 Edition APK/LMV/Airco   1799.0
62762        2.4 Kinetic LPG-G3 NAP/LEER/NAVI/DAK/NW APK   1999.0
62763  2.0T Edition,1e Eigenaar,LPG G3,Onderbouw,Navi...   3449.0
62764                                                2.4   1650.0
62765      2.4 Airco, Cruise Control, Stuurbekrachtiging    944.0

             mileage          gearbox registration fuel_type  power  \
0      191066.000000  \n,Automatic,\n      08/2003  Gasoline    150
2      145102.000000  \n,Automatic,\n      06/2015  Gasoline    125
3      119666.000000  \n,Automatic,\n      10/2015  Gasoline    125
4       55815.000000  \n,Automatic,\n      10/2017  Gasoline    150
5       47536.000000  \n,Automatic,\n      03/2019  Gasoline    116
...              ...              ...          ...       ...    ...
62761  298160.000000     \n,Manual,\n      12/2000       LPG    170
62762  104133.033982     \n,Manual,\n      02/2005       LPG    140
62763  340257.000000     \n,Manual,\n      08/2004       LPG    179
62764  104133.033982     \n,Manual,\n      01/2004       LPG    140
62765  104133.033982     \n,Manual,\n      09/2001       LPG    141

               seller body_type  type drivetrain seats doors country_version  \
0              Dealer   Compact  Used      Front     5     3            None
2              Dealer   Compact  Used       None     5     5     Netherlands
3              Dealer   Compact  Used      Front     4     3            None
4              Dealer   Compact  Used      Front     5     5            None
5              Dealer   Compact  Used      Front     5     5            None
...               ...       ...   ...        ...   ...   ...             ...
62761          Dealer     Sedan  Used      Front     5     4            None
62762          Dealer     Sedan  Used      Front     5     4            None
62763          Dealer     Sedan  Used      Front     5     4            None
62764  Private seller     Sedan  Used      Front     5     4            None
62765          Dealer     Sedan  Used      Front     5     4            None

      offer_number  warranty         Mileage first_registration  \
0         SJ-112-R  6 months  [['\n'], ['']]            08/2003
2          2601307  6 months  [['\n'], ['']]            06/2015
3         L-847-SK  6 months  [['\n'], ['']]            10/2015
4         PZ-744-H  6 months  [['\n'], ['']]            10/2017
5         L-949-SG  6 months  [['\n'], ['']]            03/2019
...            ...       ...             ...                ...
62761     52-XX-LB      None  [['\n'], ['']]            12/2000
62762     06-RB-XS      None  [['\n'], ['']]            02/2005
62763     75-PK-RN      None  [['\n'], ['']]            08/2004
62764         None      None  [['\n'], ['']]            01/2004
62765     26-HN-LS      None  [['\n'], ['']]            09/2001

      production_date general_inspection  last_service full_service_history  \
0                2003            05/2022           NaN                  Yes
2                2015            01/2024           NaN                  Yes
3                2015                NaN           NaN                  Yes
4                2017            11/2023           NaN                  Yes
5                2019                NaN           NaN                  Yes
...               ...                ...           ...                  ...
62761            2000            02/2022           NaN                  Yes
62762            2005            01/2024           NaN                  Yes
62763            2004            01/2024           NaN                  Yes
62764            2004                NaN           NaN                 None
62765            2001                NaN           NaN                 None

      non_smoker_vehicle previous_owner last_timing_belt_change  \
0                   None           None                    None
2                    Yes           None                    None
3                   None           None                    None
4                   None           None                    None
5                   None           None                    None
...                  ...            ...                     ...
62761               None           None                    None
62762               None           None                    None
62763               None              1                    None
62764               None           None                    None
62765               None           None                    None

                       Power    Gearbox  engine_size gears  cylinders  \
0      \n,110 kW (150 hp),\n  Automatic         1984  None          4
2       \n,92 kW (125 hp),\n  Automatic         1395  None          4
3       \n,92 kW (125 hp),\n  Automatic         1395     7          4
4      \n,110 kW (150 hp),\n  Automatic         1495     7          4
5       \n,85 kW (116 hp),\n  Automatic          999  None          3
...                      ...        ...          ...   ...        ...
62761  \n,125 kW (170 hp),\n     Manual         2435     5          5
62762  \n,103 kW (140 hp),\n     Manual         2435     5          5
62763  \n,132 kW (179 hp),\n     Manual         1984     5          5
62764  \n,103 kW (140 hp),\n     Manual         <NA>     5          5
62765  \n,104 kW (141 hp),\n     Manual         2435     5          5

       empty_weight                   Fuel_type  \
0       1280.000000                    Super 95
2       1433.322061                    Gasoline
3       1105.000000                    Gasoline
4       1215.000000                    Super 95
5       1180.000000                    Super 95
...             ...                         ...
62761   1501.000000                         LPG
62762   1441.000000                         LPG
62763   1495.000000                         LPG
62764   1433.322061  Liquid petroleum gas (LPG)
62765   1488.000000  Liquid petroleum gas (LPG)

                                        fuel_consumption  \
0                                                   None
2      0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...
3      4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...
4      5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...
5                                   5.1 l/100 km (comb.)
...                                                  ...
62761                                               None
62762                                               None
62763  9.1 l/100 km (comb.), 12.6 l/100 km (city), 7 ...
62764                                               None
62765  8.4 l/100 km (comb.), 11.6 l/100 km (city), 6....

       co2_emissions ( g/km) emission_class emissions_sticker  \
0                        128         Euro 4           NoNonee
2                        128           None           NoNonee
3                        111         Euro 6           NoNonee
4                        113         Euro 6           NoNonee
5                          0           None           NoNonee
...                      ...            ...               ...
62761                    128           None           NoNonee
62762                    128           None           NoNonee
62763                    215         Euro 3           NoNonee
62764                    128           None           NoNonee
62765                    207         Euro 3           NoNonee

                                     comfort_convenience  \
0      [[Air conditioning, Armrest, Automatic climate...
2      [[Air conditioning, Armrest, Automatic climate...
3      [[Air conditioning, Armrest, Automatic climate...
4      [[Air conditioning, Armrest, Electrical side m...
5      [[Air conditioning, Automatic climate control,...
...                                                  ...
62761  [[Air conditioning, Armrest, Automatic climate...
62762  [[Air conditioning, Automatic climate control,...
62763  [[Air conditioning, Armrest, Automatic climate...
62764  [[Air conditioning, Armrest, Automatic climate...
62765  [[Air conditioning, Armrest, Automatic climate...

                                    entertainment_media  \
0                                  [[CD player, Radio]]
2      [[Bluetooth, CD player, On-board computer, USB]]
3          [[CD player, MP3, On-board computer, Radio]]
4               [[CD player, On-board computer, Radio]]
5               [[CD player, On-board computer, Radio]]
...                                                 ...
62761           [[CD player, On-board computer, Radio]]
62762           [[CD player, On-board computer, Radio]]
62763                             [[On-board computer]]
62764           [[CD player, On-board computer, Radio]]
62765                      [[On-board computer, Radio]]

                                         safety_security  \
0      [[ABS, Alarm system, Central door lock, Centra...
2      [[ABS, Central door lock with remote control, ...
3      [[ABS, Alarm system, Bi-Xenon headlights, Cent...
4      [[ABS, Alarm system, Bi-Xenon headlights, Cent...
5      [[ABS, Alarm system, Bi-Xenon headlights, Cent...
...                                                  ...
62761  [[ABS, Central door lock, Central door lock wi...
62762  [[ABS, Central door lock, Central door lock wi...
62763  [[ABS, Central door lock, Central door lock wi...
62764  [[ABS, Central door lock with remote control, ...
62765  [[ABS, Alarm system, Central door lock, Centra...

                                                  extras    \ncolour  \
0                                     [['Alloy wheels']]   \n4, Grey
2                               [['Alloy wheels (15")']]   \n4, Grey
3      [['Alloy wheels (17")', 'Shift paddles', 'Spor...  \n4, Black
4      [['Alloy wheels (17")', 'Sport seats', 'Sport ...   \n4, Grey
5                               [['Alloy wheels (16")']]   \n4, Grey
...                                                  ...         ...
62761                           [['Alloy wheels (15")']]  \n4, Black
62762                           [['Alloy wheels (15")']]   \n4, Blue
62763  [['Alloy wheels (17")', 'Automatically dimming...  \n4, Black
62764  [['Alloy wheels (16")', 'Automatically dimming...  \n4, Beige
62765                                 [['Alloy wheels']]   \n4, Grey

       \nmanufacturer_color            \npaint   upholstery_colour   \
0                       NaN  \npaint, Metallic  \nupholstery, Black
2                       NaN  \npaint, Metallic                  NaN
3                       NaN                NaN  \nupholstery, Black
4                       NaN  \npaint, Metallic  \nupholstery, Black
5                       NaN  \npaint, Metallic   \nupholstery, Grey
...                     ...                ...                  ...
62761                   NaN                NaN                  NaN
62762                   NaN                NaN                  NaN
62763                   NaN  \npaint, Metallic                  NaN
62764                   NaN  \npaint, Metallic  \nupholstery, Beige
62765                   NaN  \npaint, Metallic                  NaN

             upholstery  warranty_category  full_service_encoded  \
0             \n8, Cloth      1 year<    :                     1
2                    NaN      1 year<    :                     1
3      \n8, Part leather      1 year<    :                     1
4             \n8, Cloth      1 year<    :                     1
5             \n8, Cloth      1 year<    :                     1
...                  ...               ...                   ...
62761                NaN               NaN                     1
62762  \n8, Part leather               NaN                     1
62763  \n8, Part leather               NaN                     1
62764        \n8, Velour               NaN                     0
62765  \n8, Part leather               NaN                     0

       non_smoker_encoded fuel_cons_comb fuel_cons_city fuel_cons_country  \
0                       0           None            NaN               NaN
2                       1             0              0                 0
3                       0           4.8            5.9               4.2
4                       0             5            6.2               4.3
5                       0           5.1             NaN               NaN
...                   ...            ...            ...               ...
62761                   0           None            NaN               NaN
62762                   0           None            NaN               NaN
62763                   0           9.1           12.6                 7
62764                   0           None            NaN               NaN
62765                   0           8.4           11.6               6.5

       air_conditioning           AppleCarPlay
0                     1            [[CD player
2                     1            [[Bluetooth
3                     1            [[CD player
4                     1            [[CD player
5                     1            [[CD player
...                 ...                    ...
62761                 1            [[CD player
62762                 1            [[CD player
62763                 1  [[On-board computer]]
62764                 1            [[CD player
62765                 1    [[On-board computer

[57798 rows x 57 columns]

# Abs_encoded  as 1-0.

In [195]:
df['abs_encoded'] = df['safety_security'].str.split(',').str.get(0)

df['abs_encoded'].head()

0             [[ABS
1    [[Alarm system
2             [[ABS
3             [[ABS
4             [[ABS
Name: abs_encoded, dtype: object

In [196]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [197]:
lbe.fit_transform(df["abs_encoded"])

array([0, 5, 0, ..., 0, 0, 0])

In [198]:
# '\n', boşluklar ve tek tırnakları kaldır
df['safety_security'] = df['safety_security'].str.replace('[\n\' ]', '')

# Virgülle ayır ve ilk öğeyi alarak yeni sütunu oluştur
df['abs_encoded'] = df['safety_security'].str.split(',').str.get(0)

df['abs_encoded'].head(25)
df['abs_encoded']=lbe.fit_transform(df["abs_encoded"])
#df['abs_encoded'].unique()
df['abs_encoded']

0        0
1        5
2        0
3        0
4        0
        ..
62761    0
62762    0
62763    0
62764    0
62765    0
Name: abs_encoded, Length: 61388, dtype: int32

# 44--extras

In [199]:
df['extras'].value_counts()

extras
[['Alloy wheels (16")']]                                                                                                                                                                                               2088
[['Trailer hitch']]                                                                                                                                                                                                    1726
[['Alloy wheels']]                                                                                                                                                                                                     1549
[['Alloy wheels (17")', 'Automatically dimming interior mirror']]                                                                                                                                                      1050
[['Alloy wheels (17")']]                                                                                                                                                                                                971
                                                                                                                                                                                                                       ...
[['Automatically dimming interior mirror', 'Emergency tyre', 'Roof rack', 'Spare tyre', 'Steel wheels', 'Summer tyres', 'Voice Contro']]                                                                                  1
[['Alloy wheels', 'Roof rack', 'Sport suspension', 'Voice Contro']]                                                                                                                                                       1
[['All season tyres', 'Cargo barrier', 'Catalytic Converter', 'Spare tyre', 'Steel wheels']]                                                                                                                              1
[['Alloy wheels (17")', 'Ambient lighting', 'Automatically dimming interior mirror', 'Roof rack', 'Spare tyre', 'Sport seats', 'Summer tyres', 'Touch screen', 'Trailer hitch', 'Voice Control', 'Winter package']]       1
[['Automatically dimming interior mirror', 'Catalytic Converter', 'Electronic parking brake', 'Headlight washer system', 'Ski bag', 'Trailer hitch']]                                                                     1
Name: count, Length: 8380, dtype: int64

In [200]:
# Boşluklar ve tek tırnakları kaldır
df['extras'] = df['extras'].str.replace('[\' ]', '')

# Tek tırnakları temizle
df['extras'] = df['extras'].str.replace("'", '')


df['extras'].value_counts()

extras
[[Alloy wheels (16")]]                                                                                                                                                                           2088
[[Trailer hitch]]                                                                                                                                                                                1726
[[Alloy wheels]]                                                                                                                                                                                 1549
[[Alloy wheels (17"), Automatically dimming interior mirror]]                                                                                                                                    1050
[[Alloy wheels (17")]]                                                                                                                                                                            971
                                                                                                                                                                                                 ...
[[Automatically dimming interior mirror, Emergency tyre, Roof rack, Spare tyre, Steel wheels, Summer tyres, Voice Contro]]                                                                          1
[[Alloy wheels, Roof rack, Sport suspension, Voice Contro]]                                                                                                                                         1
[[All season tyres, Cargo barrier, Catalytic Converter, Spare tyre, Steel wheels]]                                                                                                                  1
[[Alloy wheels (17"), Ambient lighting, Automatically dimming interior mirror, Roof rack, Spare tyre, Sport seats, Summer tyres, Touch screen, Trailer hitch, Voice Control, Winter package]]       1
[[Automatically dimming interior mirror, Catalytic Converter, Electronic parking brake, Headlight washer system, Ski bag, Trailer hitch]]                                                           1
Name: count, Length: 8380, dtype: int64

In [201]:
df['extras'].isnull().sum()

0

# 45--manifacturer_colour

In [231]:
df['\nmanufacturer_color'].unique() # hepsi nan değer oldğu icin silebiliriz.

KeyError: '\nmanufacturer_color'

In [230]:
df = df.drop('\nmanufacturer_color',inplace=True, axis=1)

KeyError: "['\\nmanufacturer_color'] not found in axis"

# 46-colour

In [204]:
df.rename(columns = {'\ncolour':'colour'}, inplace = True)
df["colour"].unique()

array(['\n4, Grey', '\n4, White', '\n4, Black', '\n4, Red', '\n4, Silver',
       '\n4, Brown', '\n4, Blue', '\n4, Violet', nan, '\n4, Beige',
       '\n4, Yellow', '\n4, Green', '\n4, Orange', '\n4, Bronze',
       '\n4, Gold'], dtype=object)

In [205]:
df["colour"]=df["colour"].str.strip(',\n4,')
df["colour"].value_counts()

colour
Grey      20234
Black     15615
White      8743
Blue       7654
Red        2770
Brown      1671
Silver     1582
Green       765
Beige       506
Orange      325
Yellow      257
Violet      148
Gold         48
Bronze       34
Name: count, dtype: int64

# 47 --paint

In [206]:
# Sütun adını değiştir
df.rename(columns={'\npaint': 'paint'}, inplace=True)

# Benzersiz değerleri yazdır
print(df['paint'].unique())

# Sütunu yazdır
print(df['paint'])

['\npaint, Metallic' nan]
0        \npaint, Metallic
1                      NaN
2        \npaint, Metallic
3                      NaN
4        \npaint, Metallic
               ...
62761                  NaN
62762                  NaN
62763    \npaint, Metallic
62764    \npaint, Metallic
62765    \npaint, Metallic
Name: paint, Length: 61388, dtype: object

In [207]:
df["paint"]=df["paint"].str.strip("\n ,")
df["paint"]=df["paint"].str.replace('Metallic','')
df["paint"].head()

0    paint,
1        NaN
2    paint,
3        NaN
4    paint,
Name: paint, dtype: object

In [208]:
lbe.fit_transform(df["paint"])   # burada da 0-1 e dönüitürüyoruz
df['paint']=lbe.fit_transform(df["paint"])
df['paint'].head()

0    0
1    1
2    0
3    1
4    0
Name: paint, dtype: int32

# 48-upholstery_colour

In [209]:
df[' upholstery_colour '].unique()

array(['\nupholstery, Black', nan, '\nupholstery, Grey',
       '\nupholstery, Brown', '\nupholstery, Other',
       '\nupholstery, Beige', '\nupholstery, Red', '\nupholstery, Yellow',
       '\nupholstery, Blue', '\nupholstery, White', '\nupholstery, Green',
       '\nupholstery, Orange'], dtype=object)

In [210]:
# Sütun adını değiştir
df.rename(columns={' upholstery_colour ': 'upholstery_colour'}, inplace=True)

# Boşlukları ve belirli metni değiştir
df['upholstery_colour'] = df['upholstery_colour'].str.strip()  # Boşlukları kaldır
df['upholstery_colour'] = df['upholstery_colour'].str.replace('\nupholstery,', '')  # Belirli metni değiştir



# Eksik değerleri kontrol et
print(df['upholstery_colour'].isna().sum())

21434

# 49-upholstery

In [211]:
df[" upholstery "].unique()

array(['\n8, Cloth', nan, '\n8, Part leather', '\n8, Full leather',
       '\n8, alcantara', '\n8, Other', '\n8, Velour'], dtype=object)

In [212]:
df.rename(columns={' upholstery ':'upholstery'},inplace = True)
df["upholstery"]=df["upholstery"].str.replace('\n8,','')
df["upholstery"].isna().sum()

10482

# Check Data

In [233]:
df.describe()

,price,mileage,power,engine_size,cylinders,empty_weight,co2_emissions ( g/km),paint,full_service_encoded,non_smoker_encoded,air_conditioning,abs_encoded
count,61388.000000,61388.000000,61388.000000,56329.0,61388.000000,61388.000000,61388.000000,61388.000000,61388.000000,61388.000000,61388.000000,61388.000000
mean,19226.642499,104133.033982,157.175034,1768.474676,4.065534,1433.322061,128.237098,0.292891,0.685101,0.080358,1.419382,0.518391
std,12780.784339,82310.482903,71.395084,655.166033,0.898894,318.325139,53.761537,0.455093,0.464479,0.271848,3.126526,2.523928
min,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8945.000000,30000.000000,116.000000,1390.0,4.000000,1235.000000,116.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,17450.000000,95195.000000,143.000000,1598.0,4.000000,1390.000000,128.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,25291.250000,160478.500000,170.000000,1995.0,4.000000,1585.000000,151.000000,1.000000,1.000000,0.000000,1.000000,0.000000
max,58895.000000,363000.000000,843.000000,12100.0,12.000000,4200.000000,405.000000,1.000000,1.000000,1.000000,49.000000,40.000000

In [243]:
df.isna().any()

location                   False
make                       False
model                      False
short_description          False
price                      False
mileage                    False
registration               False
fuel_type                  False
power                      False
body_type                  False
type                       False
drivetrain                 False
seats                      False
doors                      False
warranty                   False
production_date             True
general_inspection          True
full_service_history       False
non_smoker_vehicle         False
last_timing_belt_change    False
Gearbox                    False
engine_size                 True
gears                      False
cylinders                  False
empty_weight               False
fuel_consumption           False
co2_emissions ( g/km)      False
emission_class             False
emissions_sticker          False
comfort_convenience        False
entertainment_media        False
safety_security            False
extras                     False
colour                      True
paint                      False
upholstery_colour           True
upholstery                  True
warranty_category           True
full_service_encoded       False
non_smoker_encoded         False
fuel_cons_comb             False
fuel_cons_city              True
fuel_cons_country           True
air_conditioning           False
AppleCarPlay               False
abs_encoded                False
dtype: bool

In [237]:
df["short_description"].value_counts()

short_description
1.4 TSI Highline                                      58
i                                                     51
i High Executive                                      45
i Executive                                           41
77 kWh 204 pk Elektrisch Automaat Pro leverbaar 20    35
                                                      ..
Bestel 110 CDI 343 dubbele cabine✅Nap✅                 1
110 CDI 320 / AIRCO / 3-ZITS / TREKHAAK / CRUISE       1
108 CDI Lang ,Navigatie, Airco, Kastinrichting         1
108 CDI Lang ,Airco, Navigatie, LMV. al va 129,- p     1
2.4 Airco, Cruise Control, Stuurbekrachtiging          1
Name: count, Length: 53143, dtype: int64

In [238]:
df["short_description"].isna().sum()

146

In [239]:
df["short_description"] = df["short_description"].fillna("No info")

In [240]:
df["short_description"].isna().sum()

0

In [241]:
df.drop('seller',inplace=True, axis=1)

In [253]:
pd.set_option('display.max_columns', None)
df.head()

,location,make,model,short_description,price,mileage,registration,fuel_type,power (hp),body_type,type,drivetrain,seats,doors,warranty,production_date,general_inspection,full_service_history,non_smoker_vehicle,last_timing_belt_change,Gearbox,engine_size,gears,cylinders,empty_weight,fuel_consumption,co2_emissions ( g/km),emission_class,emissions_sticker,comfort_convenience,entertainment_media,safety_security,extras,colour,paint,upholstery_colour,upholstery,warranty_category,full_service_encoded,non_smoker_encoded,fuel_cons_comb,fuel_cons_city,fuel_cons_country,air_conditioning,AppleCarPlay,abs_encoded
0,"LOON OP ZAND,NL",Audi,A3,2.0 FSI Ambition Pro Line,4450.0,191066.0,08/2003,Gasoline,150,Compact,Used,Front,5,3,6 months,2003,05/2022,Yes,None,None,Automatic,1984,None,4,1280.000000,None,128,Euro 4,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, Radio]]","[[ABS, Alarm system, Central door lock, Centra...",[[Alloy wheels]],Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,None,NaN,NaN,1,[[CD player,0
1,"HEERLEN,NL",Audi,A3,Sportback 1.4 TFSI Ambiente/ECC/PDC//Lichtmeta...,12950.0,94758.0,10/2013,Gasoline,125,Compact,Used,Front,5,5,None,2013,01/2024,Yes,None,None,Automatic,1395,None,4,1200.000000,4.9 l/100 km (comb.),128,None,NoNonee,"[[Air conditioning, Automatic climate control,...","[[CD player, Radio]]","[[Alarm system, Central door lock, Central doo...","[[Alloy wheels (16"")]]",White,1,"upholstery, Black",Cloth,NaN,1,0,4.9,NaN,NaN,1,[[CD player,5
2,"BAARLENASSAU,NL",Audi,A1,1.4 TFSI Sportback Pro-Line Aut. S-Tronic Navi.,12450.0,145102.0,06/2015,Gasoline,125,Compact,Used,No Info,5,5,6 months,2015,01/2024,Yes,Yes,None,Automatic,1395,None,4,1433.322061,"0 l/100 km (comb.), 0 l/100 km (city), 0 l/100...",128,None,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[Bluetooth, CD player, On-board computer, USB]]","[[ABS, Central door lock with remote control, ...","[[Alloy wheels (15"")]]",Grey,0,NaN,NaN,1 year< :,1,1,0,0,0,1,[[Bluetooth,0
3,"ZUTPHEN,NL",Audi,A1,S-Line | Automaat | Navigatie | Cruise-/Climat...,14945.0,119666.0,10/2015,Gasoline,125,Compact,Used,Front,4,3,6 months,2015,01/2024,Yes,None,None,Automatic,1395,7,4,1105.000000,"4.8 l/100 km (comb.), 5.9 l/100 km (city), 4.2...",111,Euro 6,NoNonee,"[[Air conditioning, Armrest, Automatic climate...","[[CD player, MP3, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Shift paddles, Sport sea...",Black,1,"upholstery, Black",Part leather,1 year< :,1,0,4.8,5.9,4.2,1,[[CD player,0
4,"HAAKSBERGEN,NL",Audi,A3,Sportback 1.5 TFSI Sport | Dealer Onderhouden ...,24900.0,55815.0,10/2017,Gasoline,150,Compact,Used,Front,5,5,6 months,2017,11/2023,Yes,None,None,Automatic,1495,7,4,1215.000000,"5 l/100 km (comb.), 6.2 l/100 km (city), 4.3 l...",113,Euro 6,NoNonee,"[[Air conditioning, Armrest, Electrical side m...","[[CD player, On-board computer, Radio]]","[[ABS, Alarm system, Bi-Xenon headlights, Cent...","[[Alloy wheels (17""), Sport seats, Sport suspe...",Grey,0,"upholstery, Black",Cloth,1 year< :,1,0,5,6.2,4.3,1,[[CD player,0